### ISSUE TITLE
XML output for Jenkins intergration

### ISSUE THREAD

**Issue by RichardGuion** [square/spoon#100]
I have Spoon executed through a Jenkins job and it works fine.  In addition to the super nice HMTL reports that Spoon produces (which I was able to provide a link to in the build artifacts), people in the company would like to see Jenkins consume an XML file with the test results.  We could then turn on the Post build action "Publish JUnit test result report" and get the graph with the Test Result trend and table breakdown of the tests that were executed, pass/fail state, duration, etc.

Do you have any plans to add this to Spoon?

If not, I can take a crack at it.  It seems like the file result.json has all the data.  I could read that in and generate the XML in the format required for Jenkins.

**Comment by tandroidt** [comment]
HI where can I find this report? 
I asked  in a separated issue and been told it is in "junit-reports" folder, but I don't have this folder on the device not on the Jenkins slave. 
I can't find any documentation about to where it is generated, and if it is generated by default or I should add something to the command to get it.
This is how I run spoon now :

java -jar $SPOON_JAR --apk $APK_PATH --test-apk $TEST_APK_PATH --output $SPOON_REPORT_PATH --title "$TITLE" --class-name $TEST_SUITE_CLASS

Please help me! 
Thanks!
