### ISSUE TITLE
Retry Failed Tests

### ISSUE THREAD

**Issue by RichardGuion** [square/spoon#101]
Whenever I've worked on any kind of automated UI tests, one problem has always plagued me: tests that fail due to some random error.  Could be a network error, could be your stage server going down for a reboot, or it could just be not coding your test correctly.  Let's say you had 100 tests running across 10 Android devices.   7 of them fail due to a variety of factors.  You'd like to have executed all of the tests and time is ticking--rather than re-run the entire suite, I'd rather just re-run those 7 failed tests.

One way of accomplishing this is adding a retry option to SpoonRunner:

java -jar ~/dev/libs/spoon-runner-1.0.3-jar-with-dependencies.jar ... --retry X

This would catch each test failure as it happened and re-run it right at that moment.  What's even more complicated here, is that I don't believe in wiping out history.  I want to keep the failed test result, just in case I see a problem in the logs, and have a new result for the re-run.  The other reason I don't like this is that maybe some server was down, I need to reconcile that factor before re-running tests.

The other way to do it is to add a flag to re-run failed tests based on the results from any Spoon output folder.

java -jar ~/dev/libs/spoon-runner-1.0.3-jar-with-dependencies.jar ... --run-failed-tests ~/reports/testrun_052213/results.json

You would issue this command after doing your big test run with 100 tests on 10 devices, to retry just those 7 failed tests.

I've actually got this second way hacked up in SpoonRunner.  It does the following:
- Get the results.json file path from the new --run-failed-tests argument.
- Uses GSON.fromJson to de-serialize it back into SpoonSummary class
- Loop thru the results, looking for Device Test Results where Status != Pass
  - Re-run this single test on device X where it failed, saving output in a new sub-folder  

If these 7 tests passed and I know the reason for the first failure was due to external circumstances, I can declare the test run as successful.  I will keep the original test results along with the re-run to show what happened.

Have you guys had the same need to re-run failed tests?  What do you think of this solution?

**Comment by ijunes** [comment]
@FlakyTest no longer supports this feature. Can we reopen?

**Comment by JakeWharton** [comment]
You can write a test rule that catches exceptions and retries tests
multiple times. Otherwise I would create a custom test runner that offered
the functionality. Putting it inside the test harness software seems like
the wrong level, though.
