### ISSUE TITLE
Upgrade app testing with Spoon

### ISSUE THREAD

**Issue by RichardGuion** [square/spoon#110]
I would like to test certain app upgrade scenarios, where is a user is already logged into the app with existing data.  Then I would install the new apk and when I run the test, verify that the app can read the existing data.

This is a bit difficult with Spoon as you have this code in SpoonDeviceRunner run method:

```
try {
  // First try to uninstall the old apks.  This will avoid "inconsistent certificate" errors.
  tryToUninstall(device, instrumentationInfo.getApplicationPackage());
  tryToUninstall(device, instrumentationInfo.getInstrumentationPackage());

  // Now install the main application and the instrumentation application.
  String installError = device.installPackage(apk.getAbsolutePath(), true);
  if (installError != null) {
```

I can appreciate uninstalling the old apks--it really is useful.  However in this upgrade test scenario I would have to skip that.  I know you hate adding more options, I can just add my enhancement here locally.

Is there another way to test upgrades using Spoon that I am not seeing?

**Comment by Bald-e** [comment]
... All i have to say...
