### ISSUE TITLE
Method name does not start with 'test'.

### ISSUE THREAD

**Issue by fluxtah** [square/spoon#135]
I am trying to run some tests using the android example for cucumber-jvm (https://github.com/cucumber/cucumber-jvm/tree/master/examples/android) but spoon throws an exception when prettifying the method name in HtmlUtils.prettifyMethodName(...):  

```
  if (!methodName.startsWith("test")) {
      throw new IllegalArgumentException("Method name does not start with 'test'.");
    }
```
Is it ok to remove this requirement?

Would it be better to return the original method name instead if the condition is not satisfied?

```
    if (!methodName.startsWith("test")) {
      return methodName;
    }
```

**Comment by edenman** [comment]
This requirement is removed as of 1.1.3
