### ISSUE TITLE
Maven 3.1.x compatibility : Failed to execute goal com.squareup.spoon:spoon-maven-plugin:1.0.5:run : A required class was missing

### ISSUE THREAD

**Issue by sgrimault** [square/spoon#152]
Spoon Maven plugin is not compatible with Maven 3.1.x :

[ERROR] Failed to execute goal com.squareup.spoon:spoon-maven-plugin:1.0.5:run (default) on project xxx-instrumentation: Execution default of goal com.squareup.spoon:spoon-maven-plugin:1.0.5:run failed: A required class was missing while executing com.squareup.spoon:spoon-maven-plugin:1.0.5:run: org/sonatype/aether/resolution/ArtifactResolutionException

Maven 3.1.x use eclipse aether while Maven 3.0.x use Sonatype aether.

Thanks in advance.

**Comment by edenman** [comment]
Looks like the linked PR fixes this issue, and https://github.com/stanfy/spoon-gradle-plugin/pull/44 is the appropriate spoon gradle plugin to use, going forward.
