### ISSUE TITLE
HTML output is missing escaping

### ISSUE THREAD

**Issue by Turbo87** [square/spoon#154]
I just ran my test suite and some tests threw exceptions, which are shown in the output that spoon generates. The generated HTML looks like this:

``` html
<h4 data-toggle="collapse" data-target="#stacktrace-0">java.lang.AssertionError: Expected error <Password too long> but was <null>.</h4>
```

The exception was generated by the `fest-android` library and contains markup that looks like HTML tags to the browser and so the browser renders this as: 

> java.lang.AssertionError: Expected error but was .

It seems to me that at least the error message (possibly more?) is missing some HTML escaping.

**Comment by daj** [comment]
Is there a reason against updating [HtmlUtils.processStackTrace](https://github.com/square/spoon/blob/0e7361ea1c2926d3953a37a4f62357bc94dde3e2/spoon-runner/src/main/java/com/squareup/spoon/html/HtmlUtils.java#L192) to handle this scenario?

Example code change: https://github.com/daj/spoon/commit/b746fab2a76759c7b7592c385068bc47aae87168#diff-601ea93c1076a6e7db8985b39b0c0f8eL193

At a quick glance it seems like this might work, as the backslash character in the `\n` shouldn't get modified, which means they can still be converted to `<br/>`.

If an admin agrees this change would be okay I can test it properly.  The unit tests all pass.

**Comment by edenman** [comment]
@daj sounds good to me, PR welcome!

**Comment by Turbo87** [comment]
apparently this was fixed by https://github.com/square/spoon/pull/374

thanks @daj!
