### ISSUE TITLE
Feature: Accept optional name-value instrumentation argument pairs

### ISSUE THREAD

**Issue by sailtwist** [square/spoon#164]
(Praise) Spoon Rocks! Clean/Designed/Appropriate

As maven user, I would like to supply optional key/value test runner arguments via spoon plugin (http://developer.android.com/reference/android/test/InstrumentationTestRunner.html) so that I can:
- run my annotated tests (besides size/Large/Small etc)
  ex: -e annotation org.my.annotatedTest
- run multiple tests
  ex: -e class org.my.Test,org.my.Test2
- include perf tests
  ex: -e perf org.my.perfTest
- run my tests with a custom test runner (i.e. override what's in AndroidManifest.xml)
- pass custom key-value pairs as "-e" arguments.
  ex: -e prop1 value1

Thanks in advance!

PS: I did notice that com.android.ddmlib.testrunner.RemoteAndroidTestRunner exposes addInstrumentationArg(String name, String value)

**Comment by xCatG** [comment]
This seems to have been resolved by PR #266 right?
