### ISSUE TITLE
TimeoutException when using multiple devices/emulators

### ISSUE THREAD

**Issue by goncalossilva** [square/spoon#176]
We're frequently hitting `com.android.ddmlib.TimeoutException` when testing with multiple devices/emulators on the same machine (10 ~ 15).

After some digging, it seems ddmlib uses a 5 second timeout when sending data to each device. With a lot of devices connected simultaneously this doesn't seem to be enough, even on powerful machines. At least not all of the time.

We fixed this by setting `DdmPreferences.setTimeOut(adbTimeout);` somewhere around here: https://github.com/square/spoon/blob/master/spoon-runner/src/main/java/com/squareup/spoon/SpoonDeviceRunner.java#L147

The reason I'm not sending a PR right away is because I'm honestly unsure if this would be a proper fix, and in case it is you can easily replicate it. Namely, I'm concerned about two aspects:
1. Does it make sense to reuse adbTimeout for this?
2. Would this be the best place to do something like this?

**Comment by intelradoux** [comment]
I got the same issue. I've sended a PR.

**Comment by mmartin101** [comment]
:+1:  I am also having this issue. Using two emulators, one times out during apk install.

**Comment by edenman** [comment]
I just released 1.1.8 with this fix in it.  @goncalossilva @intelradoux @mmartin101

**Comment by mmartin101** [comment]
Thanks @edenman I just updated and it's working now :)
