### ISSUE TITLE
Unable to run spoon with multiple devices attached (OSX)

### ISSUE THREAD

**Issue by TealOcean** [square/spoon#177]
So I'm getting this error when I attach more than 1 device and run spoon with this plugin:

STDERR Error: Could not find or load main class com.squareup.spoon.SpoonDeviceRunner

My setup is:
OSX 10.9 Mavericks
Spoon 1.1.1
Robotium 5.0.1

This only occurs with more than 1 device attached.

**Comment by itsmortoncornelius** [comment]
I have the same problem, how did you fix it?

**Comment by itsmortoncornelius** [comment]
I still have the problem. Any ideas?

**Comment by FisherHUB** [comment]
Hello, I have encountered the same problem after 1.5.0 gradle and 1.2.1 runner update. It worked before. Did you manage to fix it by chance?

**Comment by trevjonez** [comment]
I have the same symptoms.

Android gradle 1.5.0
spoon 1.2.1

Is there anyway to see exactly what adb commands are being ran by spoon?

**Comment by free5ty1e** [comment]
"Nevermind figured it out!"

-Least useful comment to date.  This one is more useful than that one.  

How did you fix this?!?

**Comment by JakeWharton** [comment]
Not as bad as "+1" though. We need a comment uselessness-o-meter.

**Comment by RomainPiel** [comment]
Damn I'm stuck on that one too, would you mind explaining how you fixed it @TealOcean ?

**Comment by free5ty1e** [comment]
https://xkcd.com/979/

**Comment by pr1ntf** [comment]
+1

**Comment by Kritarie** [comment]
If anyone is still running into this, I was able to fix it by switching to this gradle plugin https://github.com/stanfy/spoon-gradle-plugin from this plugin https://github.com/x2on/gradle-spoon-plugin

**Comment by rafaelaazevedo** [comment]
@Kritarie Thanks for this :+1: It's working now, but when I open the spoon reports I still have:

java.io.FileNotFoundException: .../result.json (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.(FileInputStream.java:138)
    at java.io.FileReader.(FileReader.java:72)
    at com.squareup.spoon.SpoonDeviceRunner.runInNewProcess(SpoonDeviceRunner.java:140)
    at com.squareup.spoon.SpoonRunner$1.run(SpoonRunner.java:171)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
