### ISSUE TITLE
Espresso + spoon no screenshots

### ISSUE THREAD

**Issue by mgasiorowski** [square/spoon#188]
Hi, when I run test in Robotium everything is ok, but when I use Espresso (https://code.google.com/p/android-test-kit/), my report has blank screenshots (On all devices).

```
Spoon.screenshot(getActivity(), "ListArticleFragmentActivity");
```

![screenshot from 2014-06-30 15 14 57](https://cloud.githubusercontent.com/assets/1914132/3429726/ef451c16-0058-11e4-9fe8-b4ffbf4430f0.png)

Thanks for advice ;)

**Comment by edenman** [comment]
See also: https://github.com/square/spoon/issues/214#issuecomment-81979248
