### ISSUE TITLE
Spoon for Black Box Automation Testing

### ISSUE THREAD

**Issue by saikrishna321** [square/spoon#190]
Hi Guys, 

This looks very interesting, it would be really awesome if we can this worked with calabash-android automation tool to run our automation script on real device or emulator.

@hassox @xaviershay @eventualbuddha @JackDanger

**Comment by JakeWharton** [comment]
APKs are our bread and butter. If you can craft results into our JSON format then https://github.com/square/spoon/issues/402 covers a new method for generating the HTML report directly from it so watch that issue.
