### ISSUE TITLE
Expose screenshot method to take classname and methodname

### ISSUE THREAD

**Issue by musselwhizzle** [square/spoon#202]
I'd like to see Spoon.screenshot be overloaded to take the className and methodName as params and not just rely on the current StackTrace and trying to find them. This is extremely useful when my test class overrides "protected void runTest() throws Throwable" calls super and then wants to take a screenshot of the activity before the tearDown method is called. By doing this, I get a screenshot after each test is ran rather than having to manually call Spoon.screenshot at the end of each test. Because Spoon.screenshot looks for the runMethod to find the current testMethod it does not allow for this without reflection to call it's privates. 

Below is an example of how this is useful: 

// extends ActivityInstrumentationTestCase2

    @Override
	protected void runTest() throws Throwable {
		super.runTest();
		if (activity != null) {
			File screenshotsDir = activity.getDir("spoon-screenshots", MODE_WORLD_READABLE);
			String className = getClass().getName();
			String name = getName();
			File dirClass = new File(screenshotsDir, className);
			File dirMethod = new File(dirClass, name);

			Method method = Spoon.class.getDeclaredMethod("createDir", File.class);
			method.setAccessible(true);
			method.invoke(null, dirMethod);

			String screenshotName = System.currentTimeMillis() + "_" + "after_test" + ".png";
			File imgFile = new File(dirMethod, screenshotName);

			method = Spoon.class.getDeclaredMethod("takeScreenshot", File.class, Activity.class);
			method.setAccessible(true);
			method.invoke(null, imgFile, activity);
		}
	}

**Comment by edenman** [comment]
This will be part of 1.1.4
