### ISSUE TITLE
Espresso Spoon Client Screenshot ViewAction

### ISSUE THREAD

**Issue by mikeholler** [square/spoon#214]
It would be nice if there was a `takeScreenshot` view action packaged in the Spoon Client to support snapping a screenshot as an argument to Espresso's `perform(ViewAction...)` method.

Here is an example of what it might look like:

```java
onView(withId(R.id.myView)).perform(scrollTo(), takeScreenshot());
```

Is this something that would belong in this library? I think it would make things a lot easier, and clean up codebases, especially if the logic to discover the current activity (see #188) is also rolled into this ViewAction. I tried the following, but was unable to get it to work. Perhaps someone who knows Spoon better could use this as a starting point for implementing this:

```java
public final class SpoonScreenshotAction implements ViewAction {

    private final InstrumentationTestCase mInstrumentationTestCase;
    private final Activity mCurrentActivity;
    private final String mDescription;

    public SpoonScreenshotAction(final InstrumentationTestCase aInstrumentationTestCase,
                                 final String aDescription) throws Throwable {
        mInstrumentationTestCase = aInstrumentationTestCase;
        mDescription = aDescription;
        mCurrentActivity = getCurrentActivity();
    }

    @Override
    public Matcher<View> getConstraints() {
        return Matchers.anything();
    }

    @Override
    public String getDescription() {
        return "Taking a screenshot using spoon.";
    }

    @Override
    public void perform(final UiController aUiController, final View aView) {
        Spoon.screenshot(mCurrentActivity, mDescription);
    }

    private Activity getCurrentActivity() throws Throwable {
        mInstrumentationTestCase.getInstrumentation().waitForIdleSync();
        final Activity[] activity = new Activity[1];
        mInstrumentationTestCase.runTestOnUiThread(new Runnable() {
            @Override
            public void run() {
                activity[0] = ActivityLifecycleMonitorRegistry.getInstance()
                        .getActivitiesInStage(Stage.RESUMED).iterator().next();
            }
        });
        return activity[0];
    }

}
```

**Comment by niedzielski** [comment]
The `screenshot` / `findTestClassTraceElement` issue may be more relevant now that test cases do not necessarily extend from `InstrumentationTestCase` in Espresso 2.

**Comment by JakeWharton** [comment]
Yep. On my long to do list.

**Comment by edenman** [comment]
@mikeholler thanks for raising this when you did.  I just pushed Spoon 1.1.4 and that allows for specifying the test class name and test method name when you call Spoon.screenshot.  I've also published a gist that uses that new method to expose a ViewAction: https://gist.github.com/edenman/7fdd32a4d59ccc01185b

If we eventually move this project over to gradle, I hope to be able to pull that class into a `spoon-espresso` module, but for now a gist will do.

**Comment by daj** [comment]
In most cases I think developers will want to take a screenshot from a custom Espresso FailureHandler.  Please can you provide some advice on the best way to do this?  I've asked a Stackoverflow question about this, and added my code as an example there:    
http://stackoverflow.com/a/29929248/112705

I was left wondering in what scenarios it would be useful having SpoonScreenshotAction as a ViewAction.  Maybe there are other common examples that I'm not thinking of...  Thanks!
