### ISSUE TITLE
How would we enhance Spoon to allow us to automatically split our test suite?

### ISSUE THREAD

**Issue by daj** [square/spoon#219]
I have a large suite of independent Android tests that I am trying to speed up.  I'm hoping to find a nice way of splitting that test suite across multiple Jenkins jobs (each running its own emulator) so that I can run them in parallel, then have Spoon collect up the results.  We felt this might scale better than adding more emulators to a single cloud based Jenkins job.

I've prototyped this working with the [Fork](https://github.com/shazam/fork) library, and documented how I configured my Jenkins jobs here: http://stackoverflow.com/a/24967970/112705 

Unfortunately that approach requires a lot of manual configuration, and doesn't aggregate results together in a nice way.

We're happy to do the development work ourselves and offer the feature back as a PR.  Please can we get some guidance on whether this is a good way to solve the problem, and some pointers on what we would change in Spoon to achieve this? 

The specific things we think we need to do are:

 1. Create a custom test runner that lists all the required test cases and splits them into N partitions (we think that an up front, round robin split of those test cases would be well enough balanced for our needs).
 2. Provide a way that each of those test partitions can be run on a single device (possibly by a separate Spoon invocation in a separate Jenkins job).
 3. Provide a way to invoke the Spoon HTML-ifying of test results from the command line (so that our master Jenkins job can build a single HTML page with all the results, that may have been aggregated from the Jenkins artifacts from each sub job). 

Perhaps a more Spoon-appropriate feature would be to add an `--auto-split-test-suite` option to automatically split the test suite across all connected devices (instead of running all tests on all devices).  If so, we could work on that as a mutually useful first step?

**Comment by kakkarm001** [comment]
Hi! Have you completed the third point? What is the current status on this enhancement?
I have the same jenkins configuration and want to put the spoon records of different jobs in one html overview.

**Comment by edenman** [comment]
Current status is that there has been no progress on this.

**Comment by daj** [comment]
We have points 1 & 2 working in our custom fork of Spoon: https://github.com/cookbrite/spoon/tree/feature/multi-node

We haven't polished the code and written up the usage yet, but we've added some new parameters to configure the test sharding ([source](https://github.com/cookbrite/spoon/blob/feature/multi-node/spoon-runner/src/main/java/com/squareup/spoon/SpoonRunner.java#L441)): 

```
    @Parameter(names = { "--node-index" }, description = "Node Index of current runner")
    public int nodeIndex = 1;

    @Parameter(names = {"--node-count" }, description = "Total number of nodes")
    public int nodeCount = 1;

    @Parameter(names = {"--batch-size" }, description = "Run test in # batches")
    public int batchSize = DEFAULT_BATCH_SIZE;

    @Parameter(names = { "--filter-pattern" },
            description = "Test class name filters, comma separated, Java regex")
    public String filterPatterns;
```

**Comment by daj** [comment]
Closing this issue as Spoon now support test sharding by using its `--e` option to pass sharding arguments to the instrumentation runner.  Yay!  https://github.com/square/spoon#test-sharding
