### ISSUE TITLE
 --fail-on-failure   Non-zero exit code on failure

### ISSUE THREAD

**Issue by lukasm3** [square/spoon#222]
Any example for option:  --fail-on-failure   Non-zero exit code on failure ?

Thanks!

**Comment by edenman** [comment]
This is useful when chaining calls together on a CI machine.  In particular doing something like `java -jar spoon-runner-1.1.1-jar-with-dependencies.jar --apk example-app.apk --test-apk example-tests.apk --fail-on-failure && upload-images.sh` will not run the upload script if the tests fail.

**Comment by tandroidt** [comment]
Is it possible that fail-on-failure returns non-zero exit code only if at least half of the connected devices failed? this is kind of what i'm seeing
