### ISSUE TITLE
Screenshots not appearing during test run

### ISSUE THREAD

**Issue by RailsRoyale** [square/spoon#223]
I'm building my code in Android Studio with the spoon client and most of screenshot calls are wrapped using a:

public void takeScreenshot(String imageName)
{
    instrumentation.WaitForIdleSync();
    Spoon.screenshot( solo.getCurrentActivity(), imageName);
}

However, when I ran my tests via command line "java -jar spoon-runner.jar --apk blah --test-apk testblah" I'm not getting any screenshots whatsoever, but I am getting all of the other results. Checking the logs tell me that the screenshots were successful. I'm largely at a loss because it's not actually "failing" and so I get no diagnostics information.

**Comment by edenman** [comment]
Hrm.  Any chance you can make a test project that we can hook up a debugger to?

**Comment by RailsRoyale** [comment]
I solved the problem.
I hadn't realized that all of the images were being stored into /data/data/... and then being batched pulled off the device at the end of the test run instead of after every test.
During test execution tear down we clear the data directory to avoid saving any app state between runs.

Sorry for the noise.
