### ISSUE TITLE
Inject GSON TypeAdapter for ITestRunListener

### ISSUE THREAD

**Issue by x2on** [square/spoon#233]
I missed in #226 the fact, that if you run the tests on multiple devices the `SpoonRunner` gets serialized as json and then deserialized to an object.

If you now add a custom `ITestRunListener` it will fail with `java.lang.RuntimeException: Unable to invoke no-args constructor for interface com.android.ddmlib.testrunner.ITestRunListener. Register an InstanceCreator with Gson for this type may fix this problem.`.

So the solution would be to add a `TypeAdapter` for the `ITestRunListener`, but the `GSONBuilder` is only used in the private `SpoonUtils` static `GSON` variable.

So i can't add with `registerTypeAdapter` from outside.

Any best guess how the fix that issue?

**Comment by JakeWharton** [comment]
Registering with the Gson instance will have no effect. They will be completely different objects (it's in a different process). If you want real-time listeners we'll need an IPC mechanism from the child processes back to the parent and if we had such a mechanism, the JSON serialization could be eliminated all together.

**Comment by x2on** [comment]
Ok then i will remove my last changes with an other PR and will integrate a listener directly into spoon.
