### ISSUE TITLE
getExternalStorageDirectory() may not work well  in Nexus 5

### ISSUE THREAD

**Issue by ITanCh** [square/spoon#242]
"
Caused by: java.lang.IllegalAccessException: Unable to create output dir: /storage/emulated/0/app_spoon-screenshots
at com.squareup.spoon.Spoon.createDir(Spoon.java:164)
at com.squareup.spoon.Spoon.createDir(Spoon.java:161)
at com.squareup.spoon.Spoon.createDir(Spoon.java:161)
at com.squareup.spoon.Spoon.obtainScreenshotDirectory(Spoon.java:135)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:54)
"
/storage/emulated/0/app_spoon-screenshots may not a right file path.
REFER: http://stackoverflow.com/questions/20734564/where-is-my-sdcard-location-on-4-4-2

**Comment by edenman** [comment]
You'll need to add this permission to your `AndroidManifest.xml` for the app under test:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`

I'll add this to the README

**Comment by ITanCh** [comment]
Thanks  for your answer :)

**Comment by AAverin** [comment]
I have `java.lang.IllegalAccessException: Unable to create output dir: /storage/emulated/0/app_spoon-screenshots` on API23. Anything I have to do additionally to resolve it?

**Comment by gioPucela** [comment]
Same issue here, even after adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

**Comment by Lakedaemon** [comment]
If you target API 23 permission for WRITE_EXTERNAL_STORAGE, that is needed by spoon to create screenshots, is checked dynamically at runtime and not at install time. 
I managed to make spoon work for me by targeting Api 22 instead (but it is just a workaround :/)
A proper workaround would be to make spoon ask properly for the permission at runtime for api 23+, I guess

**Comment by tir38** [comment]
This is going to stay closed so probably best to open a new issue.

**Comment by tir38** [comment]
@Lakedaemon This should be fixed per #308
