### ISSUE TITLE
No adb logs attached to tests with Genymotion 2.4

### ISSUE THREAD

**Issue by tmelz** [square/spoon#252]
I'm not seeing any logs attached to tests in the test report. I'm running stanfy/spoon-gradle-plugin v1.0.1 (which uses spoon-runner:1.1.8) and on Genymotion 2.4 devices. I'd normally just call this an issue with Genymotion, but viewing the logs through adb on the CLI works fine.

I'm open to looking into this myself, but I'd appreciate suggestions on how to narrow down what the issue might be (with a possible/likely result of this not being a Spoon issue).

Possibly related to #251?

**Comment by tigerpenguin** [comment]
Is your test execution hanging too? I can reproduce this with the sample app as well.

Issues:
* Spoon execution doesn't complete (hangs in terminal)
* No adb logs (screen shots are generated, all html reports are generated, but logs are blank)

This is my setup:
* Android JB 4.3 x86 emulator
* JDK 7

What I tried:
* JDK 6 - same issue
* Rolled back ddmlib dependency to 23.2.8 and recompiled - same issue
* added `System.exit(0)` at the end of `SpoonRunner.main()` - well obviously this "fixes" the hanging issue...

`SpoonRunner`'s m main method is definitely exiting, since I can see the log I added for debugging.
```
[SDR.run] About to grab screenshots and prepare output for [emulator-5554]
[SDR.pullScreenshotsFromDevice] Internal path is /data/data/com.example.spoon.ordering/app_spoon-screenshots
[SDR.pullScreenshotsFromDevice] External path is /storage/sdcard/app_spoon-screenshots
[SDR.pullScreenshotsFromDevice] Pulling screenshots from [emulator-5554]
[SR.runTests] [emulator-5554] Execution done.
[SR.parseOverallSuccess] parseOverallSuccess
[SR.main] Test finished...?
```

@RichardGuion do you no longer have the issue?

**Comment by tigerpenguin** [comment]
So here's what I found out after trying out the different versions. In `spoon-runner` 1.1.2, everything is fine. However,
* spoon-runner 1.1.3 - no logs from this version on
* spoon-runner 1.1.6 - SpoonRunner hangs

Below are the terminal outputs for each of the versions I tested. Notice that starting on version 1.1.6 (the "hanging" version), there's no `D/ddms` message showing up.
```
v1.1.2 - doesn't hang, has logs
[SR.runTests] [emulator-5554] Execution done.
D/ddms: Waiting for Monitor thread

v1.1.3 - doesn't hang, no log
[SR.runTests] [emulator-5554] Execution done.
D/ddms: Waiting for Monitor thread

v1.1.5 - doesn't hang, no log
[SR.runTests] [emulator-5554] Execution done.
D/ddms: '/android_sdk/platform-tools/adb,kill-server' succeeded
D/ddms: Waiting for Monitor thread

v1.1.6 - hangs, no log
[SR.runTests] [emulator-5554] Execution done.

v1.1.7 - hangs, no log
[SR.runTests] [emulator-5554] Execution done.
```
I didn't recompile the spoon-runner versions, I used maven to download them
* 1.1.2 - https://search.maven.org/remote_content?g=com.squareup.spoon&a=spoon-runner&v=1.1.2&c=jar-with-dependencies
* 1.1.3 - https://search.maven.org/remote_content?g=com.squareup.spoon&a=spoon-runner&v=1.1.3&c=jar-with-dependencies
* 1.1.6 - https://search.maven.org/remote_content?g=com.squareup.spoon&a=spoon-runner&v=1.1.6&c=jar-with-dependencies

**Comment by tmelz** [comment]
My tests execute fine, but the logs aren't attached.

**Comment by edenman** [comment]
Odd that it works on 1.1.2 but not 1.1.3...we bumped the ddmlib version in 1.1.2, and that seems like the sort of thing that could have caused logs to stop coming over.  I'm guessing something changed in the test output format that we use to figure out when logging started/stopped for a particular test.

**Comment by edenman** [comment]
(I'll look into this, but probably won't happen for another day or two.  If you want to dig around and figure it out in the meantime, go for it)

**Comment by edenman** [comment]
My above comments are about the logs not being present.  Comments on the hanging issue should head back over to #251 which I've just reopened.

**Comment by tmelz** [comment]
Mind publishing 1.1.9 soonish?

**Comment by edenman** [comment]
@tmelz done.  I was hoping to hold off until we got #251 and #255 fixed, but I'm not going to have any time to work on those for the next week or two, so.

**Comment by rafaelaazevedo** [comment]
Hi guys, I am having the same problem with a device here, it's not showing any logs but it is showing the screenshots. I am using gradle plugin 1.0.3, spoon-client:1.2.0 and FUGU tablet.
