### ISSUE TITLE
Screenshot issue

### ISSUE THREAD

**Issue by RobertoIDL** [square/spoon#256]
Hi,

I've been playing with the library trying to get screenshots as part of my test cases written on Espresso. 

All was working well except for one thing. If the activity displays a Dialog and the soft keyboard then the image is not right, is not complete.

Any ideas why? Is this expected?

Let me show you what's happening.

This is my activity without the dialog

![1427475332808_loginactivityforgottenpassword](https://cloud.githubusercontent.com/assets/4457919/6872653/8961a09e-d4a2-11e4-8d80-544a2fe4903b.png)

This is the screenshot with the Dialog taken using DDMs

![device-2015-03-27-165953](https://cloud.githubusercontent.com/assets/4457919/6872685/b4c4dd6e-d4a2-11e4-9d5a-1c33c9391915.png)

And this is what Spoon is taking as the screenshot. As you can see the keyboard and the dialog don't appear. As the keyboard was hiding the text "Not created and account yet?" this doesn't appear on the picture either.

![1427475335937_loginactivityforgottenpassworddialog](https://cloud.githubusercontent.com/assets/4457919/6872699/c191b148-d4a2-11e4-9c97-2792b0249018.png)

Not sure what to do to be honest, any suggestions are welcome.

Thanks.

**Comment by JakeWharton** [comment]
Screenshot only works with the window you pass in (i.e., the activity). Dialogs have their own window.

Dupe #4.

**Comment by RobertoIDL** [comment]
First of all thanks for your time, that was fast :+1: 

I guess this is a known handicap for other people as well, I see what I can do. It would be nice to see the activity with the Dialog on top. 

Thanks again.

**Comment by JakeWharton** [comment]
We feel the same pain. Unfortunately no one was working on fixing it up
until recently. Hopefully we can address in the next months.
