### ISSUE TITLE
Could not find class: apple.awt.CGraphicsEnvironment

### ISSUE THREAD

**Issue by fantasy1022** [square/spoon#257]
When I execute multi screenshots in a test method, Spoon would generate a gif for those screenshots.
I meet an error "Could not find class: apple.awt.CGraphicsEnvironment" in OS X environment. Does it has workaround about this condition?

**Comment by JakeWharton** [comment]
We use https://github.com/rtyley/animated-gif-lib-for-java for GIFs and it doesn't reference that class directly. Are you using a modern JDK? Do you have a whole stack trace?

**Comment by fantasy1022** [comment]
I use jdk 8 but I use spoon-gradle-plugin version to run test. Maybe I should ask question there. Or do you any idea about this?

**Comment by JakeWharton** [comment]
I have no idea. We mostly use OSX as well and haven't seen this.

**Comment by roman-mazur** [comment]
It might be an issue with how classpath is generated for the spoon device runner by the Gradle plugin.
@fantasy1022 I've got a question for you in this thread. https://github.com/stanfy/spoon-gradle-plugin/issues/54

**Comment by roman-mazur** [comment]
Can be closed, as far as I understand.
