### ISSUE TITLE
Tests marked with @Ignore show as green in the spoon report

### ISSUE THREAD

**Issue by d-stout** [square/spoon#259]
Our Spoon output is reporting that tests annotated with @Ignore are passing. We are using JUnit and using TeamCity to run our tests. TeamCity is reporting that the test is ignored while Spoon is not.

**Comment by edenman** [comment]
`SpoonTestRunListener` has this:
```
  @Override public void testIgnored(TestIdentifier test) {
    // TODO Add ignored tests to the report.
    logDebug(debug, "ignored test %s", test);
  }
```

**Comment by edwin100394** [comment]
Is this solved? Any idea which part of the code can be changed to support this?

**Comment by azakordonets** [comment]
I would like to implement this feature. Do you guys have any group chat rooms or a place where people can you questions about how this project implemented? Or the only way to achieve this is to try to figure out everything myself and make a pull request ?

**Comment by edenman** [comment]
@azakordonets we're not really in any public group chat rooms, no.  the source should be pretty easy to figure out, though.

**Comment by azakordonets** [comment]
@edenman ok, then small question for you. I'm a newbie in android development and was wondering for an easy way to test changes in the library and how can i debug it ? I assume that one option is to build new version on every change, create some test project with passing, failing and ignored tests and then use this library to run tests and see results. It's a bit slow and cumbersome - maybe you can point me to something easier, or it's the only way ?

**Comment by edenman** [comment]
@azakordonets unfortunately yes, that's the easiest way right now.  Prior to https://github.com/square/spoon/pull/417 it would've been a bit easier because you could use the Sample app to verify your changes.  Might actually just be easier to go back to 7ee9e730ac9f0b8b2455235c8f4dcae61c824227 and make your changes, test them out on the sample app, and then apply your changes to master.

**Comment by azakordonets** [comment]
Ok, thanks. Will try to play around with code. I think it could be handy to show ignored tests
