### ISSUE TITLE
gradlew Spoon Total tests 0

### ISSUE THREAD

**Issue by RobertoIDL** [square/spoon#262]
Hi,

I've already raised this issue on the spoon-gradle-plugin repository, but just in case it has more visibility here.

If I run my test cases using gradlew spoon it works fine except for one device (not sure if is device specific, OS specific or what) 

Using my Nexus 4 with Android 5.0 I get the following logs:

2015-04-09 17:33:27 [STRL.testRunStarted] testCount=0 runName=com.vouchercloud.android.test
2015-04-09 17:33:27 [STRL.testRunEnded] elapsedTime=0

But If I plug a different device I get this:

2015-04-09 17:37:11 [STRL.testRunStarted] testCount=25 runName=com.vouchercloud.android.test

In both cases the device is recognized by adb devices and by spoon as it appears on the logs. But for some reason it can't find the test cases. 

Anyone has any ideas? I don't even know where to start looking at.

Thanks.

**Comment by KonstantinNemo** [comment]
Check your test instrumentation runner. In my case changing it from AndroidJUnitRunner to android.test.InstrumentationTestRunner fixed this.

**Comment by danielgomezrico** [comment]
I´m runing my tests with `./gradlew clean spoonStagingAndroidTest` because I have an `staging` buildType.
