### ISSUE TITLE
How to use spoon with a library module ?

### ISSUE THREAD

**Issue by shomnat** [square/spoon#263]
I am building an SDK which is in the form an Android studio library module that has some UI pieces which needs to be tested. I was hoping to use spoon, but realized that it needed an Application APK also. Is there any way this can used with a library module that itself is going to be a part of a client APK or is the only solution to use a sample app implementation of the library and then use spoon on that sample app APK ?

**Comment by JakeWharton** [comment]
Yes, basically. Or just use an empty app if the library is encased completely in the test app.
