### ISSUE TITLE
Use Spoon on Jenkins ?

### ISSUE THREAD

**Issue by Bukoow** [square/spoon#264]
Hi !

First, congratulations for your work, Spoon seems like a very good tool to develop Android projects !

But I've got a question : how to use Spoon with Jenkins ? 

Does it exist a plugin or a similar plugin ?

Thanks !

**Comment by JakeWharton** [comment]
There is no plugin. You can just invoke it with its command line API or integrate it as part of your build to have Jenkins run it.
