### ISSUE TITLE
Espresso tests are not distributing to all connected devices

### ISSUE THREAD

**Issue by shivarajp** [square/spoon#268]
Running espresso tests test method names starts with "test" keyword

[SR.runTests] Executing instrumentaion suite on 2 device(s)

 but actually on physical connected devices app is launched on only one device.

In build.gradle I am using AndroidJUnitRunner

testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

Espresso test method

     @Test
        public void testAudioRecording() throws Exception {
           onView(withId(EspressoRecordingTest.getId("start")))
                .perform(click());
        idlingResource = new RecordingWaitIdlingResource(waitingTime);
        //Register wait
        Log.d("","reg idl");
        Espresso.registerIdlingResources(idlingResource);
        //stop
        onView(withId(EspressoRecordingTest.getId("stop")))
                .perform(click());
    }

    How to fix this issue? please help

http://stackoverflow.com/questions/30261056/spoon-espresso-tests-are-not-distributing-to-all-connected-devices

**Comment by shivarajp** [comment]
http://stackoverflow.com/questions/30261056/spoon-espresso-tests-are-not-distributing-to-all-connected-devices

**Comment by edenman** [comment]
@shivarajp please re-open if you are still having this problem on latest Spoon.
