### ISSUE TITLE
When the end of the test is not automatically open the index.html

### ISSUE THREAD

**Issue by okhit007** [square/spoon#276]
My system is Windows7

My script is as follows:

java -jar spoon-runner-1.1.10-SNAPSHOT-jar-with-dependencies.jar --apk %apk% --test-apk %TEST_APK% --output SpoonTestResult

Start G:/SpoonTestResult/index.html

**Comment by JakeWharton** [comment]
Is this a feature request? Not only is this annoying to do cross-platform, but the machine might be headless and/or a CI server and/or remote. The easiest way to get this behavior is to keep doing it yourself.
