### ISSUE TITLE
Allow target diffence device for specify testing package

### ISSUE THREAD

**Issue by hieutc4** [square/spoon#279]
Currently,  Spoon will execute the test in all devices which are plug to PC
But I need to separate each package to each devices because of different precondition.

For example I have a project test which have a package to test for a device with WiFi and a device with LAN network And i need to run project test continuously in Jenkin with 2 above device
In this case i need an option to run test for only target device which have proper precondition.
So i can run auto test continuously in Jenkin like following:

java -jar spoon-runner-1.1.9-jar-with-dependencies.jar \
    --apk ExampleApp-debug.apk \
    --test-apk ExampleApp-debug-androidTest-unaligned.apk
    --e package=com.example.test.wifinetwork
    --device-name=[name of Device with Wifi]

java -jar spoon-runner-1.1.9-jar-with-dependencies.jar \
    --apk ExampleApp-debug.apk \
    --test-apk ExampleApp-debug-androidTest-unaligned.apk
    --e package=com.example.test.lannetwork
    --device-name=[name of Device with LAN]

This case I want an option "device-name" to run test only the proper device.
With this option, I think this tool will be more flexible to use.

**Comment by edenman** [comment]
@hieutc4 do whatever you want! https://github.com/square/spoon/pull/269/files
(or if for some reason that doesn't do what you want, fork away!)

**Comment by hieutc4** [comment]
hi Mr.Edenman

I checked all your URL, i found no way to config which device to run test 
Could you give me any suggestion?

Thank and best regards
