### ISSUE TITLE
Cucumber + Robotium + Spoon it is not showing the screenshots in the report

### ISSUE THREAD

**Issue by rafaelaazevedo** [square/spoon#288]
I am using cucumber with Spoon and Robotium, but there is some problem with the screenshots. I can see they are inside of image folder, but they are not showing in the report. 

- My runner class:

import android.os.Bundle;
import android.support.test.runner.MonitoringInstrumentation;
import cucumber.api.CucumberOptions;
import cucumber.api.android.CucumberInstrumentationCore;

@CucumberOptions(features = {"features"}, tags = {"@debug"})
public class Instrumentation extends MonitoringInstrumentation {

    private final CucumberInstrumentationCore instrumentationCore = new CucumberInstrumentationCore(this);

    @Override
    public void onCreate(final Bundle bundle) {
        super.onCreate(bundle);
        instrumentationCore.create(bundle);
        start();
    }

    @Override
    public void onStart() {
        waitForIdleSync();
        instrumentationCore.start();
    }

}

- My Given Step with Spoon.screenshot:

    @Given("^I open the login screen$")
    public void i_open_the_app() {
        mSolo = new Solo(getInstrumentation(), getActivity());

        Spoon.screenshot(mSolo.getCurrentActivity(), "initial_state", getClass().getName(), Thread.currentThread().getStackTrace()[1].getMethodName());

        assertThat(mSolo.getCurrentActivity()).isNotNull();

}

- My build.gradle:

android {
    defaultConfig {
        testApplicationId "com.example.test"
        testInstrumentationRunner "com.example.test.Instrumentation"
    }
}

when I run gradle spoon, I am getting:

2015-09-28 12:07:35 [SDR.run] Unable to find test for com.example.test.Login#getStackTrace
2015-09-28 12:07:35 [SDR.run] Unable to find test for com.example.test.LoginSteps#getStackTrace

Looks like it is not finding the tests. Am I forgetting something ?

Thank you !

**Comment by kirillzh** [comment]
Facing same issue with Spoon 1.5.7 and Cucumber. How was it resolved?

Thank you.

**Comment by cooperkong** [comment]
Why is this closed? Having same issue here

**Comment by edenman** [comment]
@rafaelaazevedo opened and closed this issue.  @rafaelaazevedo?

**Comment by cooperkong** [comment]
Got this working finally, looks like we need to set the testClassName to our feature name, and testMethodName to our scenario name, otherwise Spoon doesn't display the screenshot even though the screenshots are pulled into images folder.
Either hardcode these names, or use reflection.

**Comment by kirillzh** [comment]
@cooperkong, is there a way to get feature name in runtime?

**Comment by cooperkong** [comment]
@kirillzh  are you talking about the Feature name or the Gievn When Then statement in the scenario body? Actually you can get all of those at runtime via reflection through CucumberExecutor object.

**Comment by kirillzh** [comment]
@cooperkong, I am talking about the Feature name.
I don't have experience with reflection... I see that `CucumberExecutor` object is defined in `CucumberInstrumentationCore` class but it's private.

**Comment by kirillzh** [comment]
@cooperkong, something like this?
```
CucumberInstrumentationCore.class.getDeclaredField("cucumberExecutor");
```

**Comment by cooperkong** [comment]
@kirillzh 
I have created a sample project at  @[https://github.com/cooperkong/ACucumberSpoonScreenshots](url), you might find that helpful

Cheers,

**Comment by kirillzh** [comment]
Thank you very much, @cooperkong. It's definitely very helpful!

By the way I noticed your report doesn't have device logs either. There is closed issue #291 without any solution.

**Comment by cooperkong** [comment]
umm, I'm also seeing empty logs here, definitely worth investigating. I reckon we should probably stop expanding this thread anymore. I have created an enhancement

**Comment by cooperkong** [comment]
@kirillzh 
I have updated my sample [project](https://github.com/cooperkong/ACucumberSpoonScreenshots) to support Log showing in the Spoon report now.
