### ISSUE TITLE
Cucumber + Spoon + Robotium

### ISSUE THREAD

**Issue by rafaelaazevedo** [square/spoon#289]
I am using Cucumber with Spoon and even that I am using the screenshot with classname and method param:        
Spoon.screenshot(mSolo.getCurrentActivity(), mTag, mClassName, mMethodName);

Spoon is building the report with the name of the feature and the name of the scenario, not with the name of the class and the method that I am sending. So, it's not finding the screenshots to put in the report. 

This screenshot method could generate and put the screenshots following just these params (class name and method name), because now Spoon is not following the same structure.

**Comment by edenman** [comment]
Pretty sure this is fixed in 1.3.1
