### ISSUE TITLE
Log empty [Cucumber + Robotium + gradle]

### ISSUE THREAD

**Issue by rafaelaazevedo** [square/spoon#291]
I am running spoon with cucumber, I can take the screenshots and put them in the report, but I am having problems with the logs. For some unknown reason the log is empty. I found some closed bugs here, but is still happening for me.

I am using FUGU and PIPO devices. Thank you !

**Comment by edenman** [comment]
@rafaelaazevedo I think this is a dup of #302

**Comment by kirillzh** [comment]
@rafaelaazevedo, was it solved by fixing #302? Cause I get empty logs, too, even with latest Spoon 1.5.7 runner.

Thank you.

**Comment by cooperkong** [comment]
Yeah, I can also confirm 1.5.7 is giving empty log messages when running Cucumber tests.

**Comment by cooperkong** [comment]
Resolved by creating customised Reporter from Cucumber, please have a look at my sample project [here](https://github.com/cooperkong/ACucumberSpoonScreenshots).
