### ISSUE TITLE
Screenshots fail on 6.0 when the app doesn't hold the WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by MichaelEvans** [square/spoon#292]
If the app doesn't request the `write_external_storage` permission, on <= L, you can add the permission to the tested variant's manifest, which through the magic of the manifest merger, will allow the for Spoon to take screenshots. 

On M however, simply adding the permission to the manifest doesn't actually grant it. A possible workaround would be to grant permission with adb. 
```
grant <PACKAGE_NAME> <PERMISSION>
```

**Comment by pvegh** [comment]
I think something like this in *setUp()* would be more elegant, since it actually runs before every single test (which is very good in this case).
````
if (ContextCompat.checkSelfPermission(getActivity(), Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_DENIED) {
            ActivityCompat.requestPermissions(getActivity(), {Manifest.permission.WRITE_EXTERNAL_STORAGE}, 1);
        }
```

**Comment by JakeWharton** [comment]
Tests are not meant to be interactive and that call will not block the test from running without the permission.

**Comment by hannesstruss** [comment]
Can we use `getExternalCacheDir()`? [No permissions needed](http://developer.android.com/reference/android/content/Context.html#getExternalCacheDir()) for that starting with KitKat.

**Comment by edenman** [comment]
This should be fixed.
