### ISSUE TITLE
How to contribute ? 

### ISSUE THREAD

**Issue by mfarid** [square/spoon#294]
Hi 

How can one contribute to spoon? I am trying to build the master branch but I am getting an error: 

[ERROR] Failed to execute goal on project spoon-runner: Could not resolve dependencies for project com.squareup.spoon:spoon-runner:jar:1.2.1-SNAPSHOT: Failure to find com.squareup.spoon:spoon-client:jar:1.2.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

Is there any mailing list which I can subscribe and post my queries to?

**Comment by mfarid** [comment]
Please ignore the problem I mentioned, it was mistake from my end. I was building a module without building the entire project.

**Comment by edenman** [comment]
There's no mailing list, just post questions/proposals here as github issues.
