### ISSUE TITLE
Bug in Parsing arguments for Runner

### ISSUE THREAD

**Issue by EugeneDeveloper** [square/spoon#297]
Spoon-runner has a bug in passing arguments for android instruments.
Now we have possibility to pass arguments for Custom TestCase runner. Using for that instrumentationArgs variable. Now syntax name=value. After that parsing search '=' symbol. This is wrong. Because in "value" possible also be a '='. example 
name=http://link?ref=sfsdfdsfds
```
if (instrumentationArgs != null && instrumentationArgs.size() > 0) {
        for (String pair : instrumentationArgs) {
          String[] kvp = pair.split("=");
          if (kvp.length != 2 || isNullOrEmpty(kvp[0]) || isNullOrEmpty(kvp[1])) {
            continue;
          }
          runner.addInstrumentationArg(kvp[0], kvp[1]);
        }
      }
```
We should use Regex for dividing this.
This is a bug.

**Comment by JakeWharton** [comment]
You don't need regex. Split can limit and there's also MapSplitter in Guava.

**Comment by EugeneDeveloper** [comment]
I agree. It's possible to use some different things. The main idea that splitter should not be the '=' symbol. Because if I use some '=' in  arguments the value is broken. Example 
> Argument1="http://link?ref=sfsdfdsfds"
Here we have 2 '='. Current code doesn't process it correctly. Please, could you fix it. Thanks in advance.

> 4 нояб. 2015 г., в 18:43, Jake Wharton <notifications@github.com> написал(а):
> 
> You don't need regex. Split can limit and there's also MapSplitter in Guava.
>

**Comment by JakeWharton** [comment]
As I said, there's nothing wrong with split. It just needs limited to
return only 2 items.

**Comment by EugeneDeveloper** [comment]
Can we get this hot fix on next build? Thanks for quick response?

**Comment by JakeWharton** [comment]
Sure. Want to send a PR?

**Comment by EugeneDeveloper** [comment]
I so like your service. I am steal investigating service. We are going to use it on big projects. What do you think about PR? Thanks

> 6 нояб. 2015 г., в 13:01, Jake Wharton <notifications@github.com> написал(а):
> 
> Sure. Want to send a PR?
>
