### ISSUE TITLE
Spoon as a standalone tool (Using custom testRunner)

### ISSUE THREAD

**Issue by EugeneDeveloper** [square/spoon#299]
You mentioned that possible run Spoon as a standalone tool with your application and instrumentation APKs. Previously I used gradle plugin and param like "testInstrumentationRunner". I didn't see this param in your list.
Can we now select custom testRunner during execution Spoon as a standalone tool (Using Jar file)? I need custom testRunner for access arguments in TestCase. Thanks.

**Comment by EugeneDeveloper** [comment]
I found that testInstrumentationRunner should be define before compiling a test apk. 
I didn't found a param for target device. Not if I use spoon as java tool I cannot customize target device name.

**Comment by edenman** [comment]
Sorry, missed this when you originally posted it.  @EugeneDeveloper I'm going to close this....let me know if you're still unclear on how the standalone runner works.
