### ISSUE TITLE
ddmlib 24.5.0 - API Change

### ISSUE THREAD

**Issue by x2on** [square/spoon#300]
Hi,

in the ddmlib 24.5.0 (comes with gradle-android plugin 1.5.0), the API for `IDevice.installPackage` has changed.

Do you see any problems for upgrading to the newest version?

Otherwise my gradle plugin would not work anymore (see https://github.com/x2on/gradle-spoon-plugin/issues/13)

**Comment by x2on** [comment]
@edenman: Are there any plans for a new release? Would be great :)

**Comment by ligi** [comment]
+1 for a release including this change

**Comment by edenman** [comment]
@x2on @ligi yup, can do later today.

**Comment by edenman** [comment]
1.2.1 released, should be live on maven central in a couple hours.  thx again!

**Comment by ligi** [comment]
:+1 great - this was fast !-)

**Comment by ouguangqian** [comment]
I Update Gradle plugin to v.1.5.0 and Update to ddmlib 24.5.0,bug i also have the problem

* What went wrong:
Execution failed for task ':app:spoonDebugAndroidTest'.
> com.android.ddmlib.IDevice.installPackage(Ljava/lang/String;Z[Ljava/lang/String;)Ljava/lang/String;

the follows is my gradle file:
apply plugin: 'com.android.application'


buildscript {
    repositories {
        jcenter()
    }
    dependencies {
//        该版能生成报告
        classpath 'com.android.tools.ddms:ddmlib:24.5.0'
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.2'
    }
}

apply plugin: 'spoon'


android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.pateo.autotest"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        minSdkVersion 18
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.0.1'

//     Instrumentation tests
//    androidTestCompile 'com.android.support.test.espresso:espresso-contrib:2.1'

    androidTestCompile 'com.android.support.test:runner:0.4'
    // Set this dependency to use JUnit 4 rules
    androidTestCompile 'com.android.support.test:rules:0.4'

    androidTestCompile 'com.android.support.test.uiautomator:uiautomator-v18:2.1.2'
//    spoon 测试框架
    androidTestCompile 'com.squareup.spoon:spoon-client:1.2.1'
}

**Comment by edenman** [comment]
@ouguangqian it looks like spoon-gradle-plugin hasn't been updated to point at spoon-runner 1.2.1.  You can either submit a PR to that project to upgrade, or just live with it being broken in 24.5.0 for now.
