### ISSUE TITLE
Aggregate sharded test runs into a single summary

### ISSUE THREAD

**Issue by LesterTheTester** [square/spoon#311]
Looking at the code, it seems the summary generation is strictly tied to the serials being executed in the current run.  So when we run our sharded tests, while we get per-serial reports in the device and junit-reports folders, our index.html is just the summary of the last shard to finish running.

Right now, we sidestep this by specifying a different --output for each of our shard runs, and then use a script to generate our own aggregated summary page.  It would be great if spoon provided an option for producing an aggregated summary.

**Comment by edenman** [comment]
I won't have time to do this and I'm not exactly sure what this would look like as part of Spoon: what's the tool you're using to shard the tests?  Regardless, PRs welcome!

**Comment by LesterTheTester** [comment]
We're passing the numShards and shardIndex parameters via --e as documented: https://github.com/square/spoon#test-sharding

If I'm tempted to put together a PR, does anyone have a preferred approach?  My thoughts are that I'd like to kick off all the shards from a single spoon command, instead of running 4 separate ones, that would seem to allow me to not have to modify the summary code much. At a high level:

java -jar spoon-runner-1.3.1-jar-with-dependencies.jar \
    --apk ExampleApp-debug.apk \
    --test-apk ExampleApp-debug-androidTest-unaligned.apk \
    --shards 4

Then internally the numShards and shardIndex for each of the android instrumentation runners that are launched.

**Comment by edenman** [comment]
Oh, ha.  Totally forgot we added sharding support.  Yeah, I like that approach, go for it!

**Comment by xCatG** [comment]
Our use case is to run spoon on different Jenkins slave jobs so I was thinking about aggregating the result.json back to the Jenkins master job (master as for Jenkin's multi-configuration job) and then read the result.json back into `DeviceResult` and pass it to `HtmlRenderer.render()` somehow.
But I couldn't find a way to run code on Jenkins Master node, so I never explored further.  If @LesterTheTester  has PR for the aggregation, I'd love to make it work on the case for separate commands.

**Comment by LesterTheTester** [comment]
I've finally gotten around to making a PR for this: https://github.com/square/spoon/pull/329

Basically, you can now specify --shard and have your tests automatically sharded across all serials specified.

Please let me know what you think. Thanks!

**Comment by edenman** [comment]
Just released in 1.4.0.  Thanks again, @LesterTheTester!
