### ISSUE TITLE
Screenshots not showing in report (Nexus 7, Android 6.0.1)

### ISSUE THREAD

**Issue by bootstraponline** [square/spoon#313]
Spoon is picking the wrong location to store the screenshots. I always get `EACCES (Permission denied)` on Android 6 even with `android.permission.WRITE_EXTERNAL_STORAGE` permission & pm grant.

If `takeScreenshot(File file, final Activity activity) ` was public then it'd be simple to save the screenshot to a location that doesn't have this problem.

> java.io.FileNotFoundException: /storage/emulated/0/app_spoon-screenshots/com.my.app.test.LoginTest/loginRejectsInvalidCredentials/1453169707921_failure.png: open failed: EACCES (Permission denied)

**Comment by JakeWharton** [comment]
Wouldn't fixing the problem be easier than exposing a new API?

**Comment by bootstraponline** [comment]
I copied the code into my own package to see if it'd solve the issue or not. I'm seeing the screenshots saved successfully, EACCES is apparently a temporary flake. The problem is they're never pulled off the device. `spoon/debug/index.html` doesn't show any screenshots and the `image/` folder is empty.

The debug logs aren't helpful so it isn't clear what's going wrong.

**Comment by JakeWharton** [comment]
The runner has no idea where the screenshots are going so it can't pull them.

**Comment by bootstraponline** [comment]
No, I'm using spoon unmodified now and it still can't pull anything. They're in the default folder `/sdcard/app_spoon-screenshots`

The debug logs don't indicate if anything was even pulled, just that it attempted to do something.

**Comment by bootstraponline** [comment]
```
2016-01-18 21:44:46 [SDR.pullDirectory] External path is /sdcard/app_spoon-screenshots
2016-01-18 21:44:46 [SDR.pullDirectory] Pulling files from external dir on [07126c81]
2016-01-18 21:44:46 [SDR.pullDirectory] Pulling files from internal dir on [07126c81]
2016-01-18 21:44:46 [SDR.pullDirectory] Done pulling app_spoon-screenshots from on [07126c81]
```

The images are there but they don't make it off the device.

**Comment by bootstraponline** [comment]
It was easier just to fork spoon and add a new API to save images to a desired location. With cloud testing services, if the images aren't in the expected folder then they don't exist.
