### ISSUE TITLE
Unable to pass comma separated value through --e 

### ISSUE THREAD

**Issue by xCatG** [square/spoon#319]
When trying to pass a comma separated value (ex, `notAnnotation`) to AndroidJUnitRunner, anything after the comma gets ignored.

for example
`--e notAnnotation=com.mycompany.Annotation1,com.mycompany.Annotation2`

gets translated into this as part of `am instrument` command
`-e notAnnotation com.mycompany.Annotation1`
where it should be
`-e notAnnotation com.mycompany.Annotation1,com.mycompany.Annotation2`

**Comment by edenman** [comment]
Are you running this from mvn command line?  Gradle plugin?  Can you paste the full line you're executing?  @Fyzxs may know more about why it's not working.

**Comment by xCatG** [comment]
@edenman I'm running this on command line using 
```
java -jar spoon-runner-1.3.1-jar-with-dependencies.jar --apk debug.apk \
--test-apk debug-androidTest.apk --no-animations --fail-on-failure --debug \
--e notAnnotation=com.mycompany.Annotation1,com.mycompany.Annotation2
```
And the corresponding am instrument command shown in debug output is
```
am instrument -w -r -e noAnnotation com.mycompany.Annotation1 \
com.mycompany.test/android.support.test.runner.AndroidJUnitRunner`
```

**Comment by Fyzxs** [comment]
@xCatG Thank you for the command. The issue arose from jCommander's helpful splitting mechanism helping where it didn't need to.

**Comment by xCatG** [comment]
@Fyzxs thanks for fixing this issue!! :-)

**Comment by edenman** [comment]
@xCatG I just pushed 1.3.2 to maven central.  should be live in a couple hours

**Comment by xCatG** [comment]
Thanks a lot @edenman!
