### ISSUE TITLE
Remove System.currentTimeMillis() in Screenshot filenames

### ISSUE THREAD

**Issue by LesterTheTester** [square/spoon#321]
Is there a good reason to do this other than to enforce extreme uniqueness? They should already be unique enough given test class name / test method name / user supplied tag. 

IMO if a user gives the same name to a screenshot within the test method, they can reasonably expect it to override the old one.  If users really want currentTimeMillis() in their filenames, they could pass it in as tag...

The context is we want to take all our screenshots from run to run and diff them with a utility like dfrnt, and this causes us to have to do some complex file renaming to remove the timestamps.  The existing testclass/testmethod/tag.png nomenclature would be perfect for this.

https://github.com/square/spoon/blob/ccbffd7e5718b2c991bf029dad04730bb8fd5410/spoon-client/src/main/java/com/squareup/spoon/Spoon.java#L81

**Comment by JakeWharton** [comment]
It orders them in the output for the website.
