### ISSUE TITLE
jar for running on Travis-Ci

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/spoon#322]
Your README instructions say:
> Download the latest runner JAR or the latest client JAR

However, if I wish to invoke Spoon in my Travis-Ci builds via the command you recommend:
`java -jar spoon-runner-1.3.1-jar-with-dependencies.jar \
    --apk ExampleApp-debug.apk \
    --test-apk ExampleApp-debug-androidTest-unaligned.apk`
then what is the **spoon-client.jar** for?

Thanks,
Igor

**Comment by JakeWharton** [comment]
Capturing screenshots and placing them in a folder that the spoon-runner understands in order to include them in the final report.

See https://github.com/square/spoon#screenshots

**Comment by IgorGanapolsky** [comment]
@JakeWharton  Thanks!  @changetip $1

**Comment by changetip** [comment]
Hi @jakewharton, @IgorGanapolsky sent you a tip worth 2,380 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/942863)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
