### ISSUE TITLE
NoClassDefFoundError on Android 4.1.2

### ISSUE THREAD

**Issue by speciosus** [square/spoon#323]
Hi, everybody.
I write because I have encountered a problem while using the spoon-client v.1.3.2 library on Samsung Galaxy S2 (Android 4.1.2) and I noticed a build conflict with Retrofit 2.
In detail, while performing any network request, the application dies with the following stack trace:

<code>
android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54) at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240) at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1619) Caused by: java.lang.NoClassDefFoundError: retrofit2.Retrofit$Builder at com.vwgroup.audiservice.network.ServiceGenerator.(ServiceGenerator.java:24) ... 33 more 
</code>

The same code runs without any issue on Android 5.0, 5.1, 6

My Gradle dependencies are as follows:

<code>
    // -- Network with retrofit
    compile('com.squareup.retrofit2:retrofit:2.0.0')
    compile('com.squareup.retrofit2:converter-gson:2.0.0')
    compile('com.squareup.retrofit2:converter-simplexml:2.0.0') {
        exclude module: 'xpp3'
        exclude module: 'stax'
        exclude module: 'stax-api'
    }

    // Espresso testing
    androidTestCompile 'com.android.support:support-annotations:23.2.1'
    androidTestCompile 'com.android.support.test:runner:0.4.1'
    androidTestCompile 'com.android.support.test:rules:0.4.1'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.1'

    androidTestCompile ('com.squareup.spoon:spoon-client:1.3.2'){
        exclude group: 'com.squareup.retrofit2'
    }
</code>

Any help will be appreciated.

thanks

**Comment by JakeWharton** [comment]
This is usually indicative of a build configuration problem, not Spoon itself. Are you using multidex?

**Comment by speciosus** [comment]
No, multidex feature is disabled: once disabled spoon, the app works greatly.

Maybe a conflict that deals with retrofit2 library?

**Comment by edenman** [comment]
What are you trying to do with `exclude group: 'com.squareup.retrofit2'`?  Spoon doesn't include retrofit 1 or 2.
