### ISSUE TITLE
Feature request: running only tests from selected package

### ISSUE THREAD

**Issue by bholota** [square/spoon#324]
**Background:** I've started working on legacy project that has instrumentation based unit tests and ui tests, Jenkins is used to run all units by default, with excluded ui tests (easy one with build.gradle and excluded source sets), those are placed in sub-package, in androidTest. I know that I can place two packages unit - ui on same level or other package juggling, exclude one and include other but I don't want to do so if spoon can handle that. Also bunch of devs will provide new test suites so It cannot depend on Jenkins config.

**Feature:** ___As a user I want to specify package with tests for spoon run.___
Other packages with tests should be ignored.

It looks like it's supported by ```RemoteAndroidTestRunner#setTestPackageName(String)```, I'll try to implement this.

**Comment by edenman** [comment]
Can use `--e package=com.some.package.ui` for this.
