### ISSUE TITLE
Screenshot is always the same 

### ISSUE THREAD

**Issue by scottlahay** [square/spoon#327]
Spoon always has the exact same screen shot, For example I run a test like this to navigate to the next page.
    @Test
    @SmallTest
    public void usersCanClickTheLoginButtonToLoginUsingTheirGetInTheLoopLogin() {
        Spoon.screenshot(getActivity(), "Welcome Page");
        solo.clickOnText("Sign in!");
        assertTrue(solo.searchText("Login Page"));
        Spoon.screenshot(getActivity(), "Login Page");
    }

Spoon shows the exact same image for both screens shots.
- I can see the app navigating properly. 
- The assertion passes before I take the second screenshot so ordering is fine.
- It happens for all the tests that I'm running. 
- My Device is a moto play on Marshmellow

Any thoughts?

**Comment by edenman** [comment]
Is the "login page" a Dialog?  Dialogs aren't captured by the spoon screenshot method.

**Comment by scottlahay** [comment]
No, Its an activity

**Comment by scottlahay** [comment]
I am seeing this bug to.  "Problem with parsing logcat output #302" could it be related?

**Comment by scottlahay** [comment]
Turns out its not a problem with Spoon but an issue with Robotium. https://github.com/robotiumtech/robotium/issues/258   The activity i was sending spoon was wrong. Please close.
