### ISSUE TITLE
No Device logs in Spoon report with espresso tests 

### ISSUE THREAD

**Issue by harjitsinghfk** [square/spoon#337]
I am not getting any device log in the spoon report. It is giving empty device logs in the report. I have tried it with spoon 1.4.0 , 1.5.1 and 1.5.2 standalone tool.

java -jar spoon-runner-1.5.2-jar-with-dependencies.jar --apk app-debug-unaligned.apk  --test-apk  app-debug-androidTest-unaligned.apk
<img width="1271" alt="screen shot 2016-05-07 at 10 34 54 pm" src="https://cloud.githubusercontent.com/assets/10266650/15093388/fd6b5d44-14a3-11e6-8114-7e95e522ca9a.png">

I have tried it on multiple devices as well no luck :(

**Comment by edenman** [comment]
Looks like a dup of https://github.com/square/spoon/issues/302, check out https://github.com/square/spoon/issues/302#issuecomment-215318261

**Comment by harjitsinghfk** [comment]
@edenman  I doubt it these issues are same as I did not get any error on the commandline.

java -jar spoon-runner-1.5.2-jar-with-dependencies.jar  --apk playstore-debug-unaligned.apk --test-apk playstore-debug-androidTest-unaligned.apk --class-name com.test.Tests 
2016-05-06 23:44:50 [SR.runTests] Executing instrumentation suite on 2 device(s).

**Comment by runpengchensc** [comment]
@harjitsinghfk we have the same issue. Do you have any updates?

**Comment by harjitsinghfk** [comment]
@runpengchensc I worked on this a while back. I think we tried with the latest version at that time.Either it was 1.5.7 or 1.5.6. Try on these versions it should work.
