### ISSUE TITLE
Don't run tests on unsupported devices

### ISSUE THREAD

**Issue by patrickhammond** [square/spoon#338]
If you have an APK where `minSdkVersion` is set to API 16 and but have a connected device running API 15, Spoon will incorrectly attempt to run tests on the unsupported device.  For what it's worth, running tests as regular Android instrumentation test (`connectedCheck`) does correctly exclude the unsupported device.

I believe the following is what would need to be enhanced to only return serial numbers of supported devices.
https://github.com/square/spoon/blob/master/spoon-runner/src/main/java/com/squareup/spoon/SpoonRunner.java#L116

**Comment by edenman** [comment]
We didn't really design spoon with this usecase in mind.  I won't have time to make this enhancement but will happily review a PR if you want to put one together?

**Comment by patrickhammond** [comment]
@edenman Glad to put together a PR. I should have something ready in the next day or two. Thanks!

**Comment by tir38** [comment]
@edenman care to mark this closed?

**Comment by edenman** [comment]
@tir38 yup, thanks!
