### ISSUE TITLE
How to run the spoon + robotium tests on multiple devices in parallel?

### ISSUE THREAD

**Issue by adheesh24** [square/spoon#348]
Hi,
Well I figured out how to run on all versions of android devices. Now I want to run the test cases on multiple devices simultaneously. But the test cases are running sequentially. Can anyone help me how to run it in parallel??
This is the way I run my tests: java -jar spoon-runner-1.5.4-jar-with-dependencies.jar --apk Calculator.apk --test-apk CalculatorTest.apk
Thanks.

**Comment by kirillzh** [comment]
Hi @adheesh24,

How did you resolve this issue?

Thanks!

**Comment by adheesh24** [comment]
You need to add these permissions in your test project manifest file.
 <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

 And add this class in your test project.

[SpoonInstrumentationTestRunner.java.zip](https://github.com/square/spoon/files/351672/SpoonInstrumentationTestRunner.java.zip)

**Comment by kirillzh** [comment]
Hi @adheesh24,

I am using [Cucumber](https://github.com/cucumber/cucumber-jvm), I can run tests only if my Instrumentation runner extends [MonitoringInstrumentation](https://developer.android.com/reference/android/support/test/runner/MonitoringInstrumentation.html) class. 
In some reason I have this issue while running tests on multiple AVDs. Works fine with Genymotion. 😕
