### ISSUE TITLE
init-script gets run for devices not included in test run

### ISSUE THREAD

**Issue by INRIX-Owais-Ali** [square/spoon#351]
Based on the description of the parameter, I would expect the script to run for each device that the tests will run on but it looks like it gets run for each connected device instead.

Specific scenario:
1) I have 3 connected physical devices on the machine
2) I specify which devices (2 of the 3 connected) to run tests on using the -s parameters (and also use auto-sharding, although I imagine this doesn't make a difference)
3) I specify an init-script to do some work on each device prior to running tests

Expected Result: init-script only runs for devices which are specified

Actual Result: init-script runs for each connected device

**Comment by edenman** [comment]
@INRIX-Owais-Ali sounds like an oversight.  PRs welcome!

**Comment by INRIX-Owais-Ali** [comment]
Looking through the code I think my understanding of what this is supposed to be doing is incorrect. The documentation says:
> Path to a script that you want to run before each device

What its actually doing is running the script before testing on any of the devices once - which is perfectly valid behavior (probably needs a change to the description of the parameter to be clearer)

The issue I'm seeing seems to be in the script itself so it's not an issue with Spoon!

**Comment by edenman** [comment]
👍
