### ISSUE TITLE
How I can run few test cases?

### ISSUE THREAD

**Issue by andreevym** [square/spoon#353]
Hi,
I want to choose few tests for each run. How I can do that?

**Comment by bholota** [comment]
Sort test suites by package and run spoon with package instrumentationArg

**Comment by JakeWharton** [comment]
We support filtering by class name and optionally test name. Additionally you can use the `--small`, `--medium`, and `--large` filters provided you're using the corresponding small/medium/large annotations on test classes. We don't have plans to support any other filtering at this time.

**Comment by andreevym** [comment]
Thanks alot but I found other solution and make custom tun each of test, around one year ago
