### ISSUE TITLE
Add --grant-all parameter to grant all runtime permissions on Marshmallow and above devices

### ISSUE THREAD

**Issue by kirillzh** [square/spoon#355]
I'd find this feature really useful to avoid granting runtime permissions via UI.

Is it something community would be interested in? I could try to work on that. Should be fairly easy. Just need to add `"-g"` extra argument in `installPackage` method for Marshmallow and above devices.

**Comment by edenman** [comment]
Sounds great, go for it.

**Comment by kirillzh** [comment]
Done!
