### ISSUE TITLE
1.6.0 screenshot in report showing as link instead of images

### ISSUE THREAD

**Issue by cooperkong** [square/spoon#358]
Hi,
Just tried the latest version, it seems like the screenshot images in the report becomes links to images.
Not sure if this is an intentional.

thanks.

**Comment by kirillzh** [comment]
Dang, looks like my pull request broke it. I'll fix it.

**Comment by kirillzh** [comment]
Because `SpoonDeviceRunner#run` method was too long and lint wouldn't let me compile, I had to move some of the code into methods and forgot to call `SpoonDeviceRunner#handleImages`.

**Comment by kirillzh** [comment]
Thanks for reporting that, @cooperkong!

**Comment by cooperkong** [comment]
@kirillzh  that was quick, thanks!

**Comment by edenman** [comment]
Just released 1.6.1 which should have this fix.  Thanks for reporting, @cooperkong!
