### ISSUE TITLE
Disabling window animations

### ISSUE THREAD

**Issue by LesterTheTester** [square/spoon#367]
When using the adb shell instrument command, it's possible to turn off window animations at test time with --no-window-animations.  Unfortunately, this is a top-level flag and not an instrumentationArg, so I don't think I can do it through spoon in it's current state.  We're interested in this because we're running headless emulators, and can't disable the window animations by the usual dev tools method.

Any ideas on how to do this through spoon? I looked into RemoteAndroidTestRunner, but it doesn't seem to allow you to configure this, just the instrumentationArgs....

**Comment by edenman** [comment]
@LesterTheTester hm.  i'm not familiar with this flag, but the docs seems to say that it's `--no-window-animation` (not plural).  try setting that as an instrumentation arg?

**Comment by edenman** [comment]
Oh nevermind, forgot that instrumentation args are the `-e` ones.

**Comment by edenman** [comment]
looks like there's a `setRunOptions(String)` on `RemoteAndroidTestRunner` and that gets passed as an argument on the `am instrument` command.  Try that?

**Comment by LesterTheTester** [comment]
Cool, I'll close this and open a pull request tomorrow.
