### ISSUE TITLE
java.lang.IllegalArgumentException: Status was already marked as FAIL

### ISSUE THREAD

**Issue by LesterTheTester** [square/spoon#369]
I've recently started to see this when a test on a device fails due to an exception:

![screenshot from 2016-08-04 16-21-48](https://cloud.githubusercontent.com/assets/4722184/17421591/cf5a11aa-5a5f-11e6-9853-e8a46d3a60bc.png)

The presence of this exception seems to preclude XML reports being generated for that device.  This is a problem because then our build system thinks everything passed, since there's no XML report generated for the device that failed.  In this case, we should have a report for emulator-5554 but we don't:

![screenshot from 2016-08-04 16-22-05](https://cloud.githubusercontent.com/assets/4722184/17421621/0f9d9660-5a60-11e6-8164-9736b663a893.png)

Any ideas of recent changes that may have caused this or areas to look? I'll try to dig in when I get the chance.

**Comment by LesterTheTester** [comment]
I made a PR for this...seems safe to allow spoon to re-mark an already failed test as long as it's setting the same status.  The only thing this seems intended to guard against is a FAIL getting changed to an ERROR...maybe we want to remove the check entirely?

**Comment by edenman** [comment]
I'm ambivalent about #370: I don't doubt that it gets rid of the issue you're seeing but I'm really more curious about why we're marking a result for the same test twice.  Can you do a `new Throwable().printStackTrace()` in `markTestAsFailed/markTestAsError` and see if the path to the double-call is the same?

**Comment by LesterTheTester** [comment]
So, looks looks like the path is exactly the same

java.lang.Throwable
 	at com.squareup.spoon.DeviceTestResult$Builder.markTestAsFailed(DeviceTestResult.java:88)
 	at com.squareup.spoon.SpoonTestRunListener.testFailed(SpoonTestRunListener.java:51)
 	at com.android.ddmlib.testrunner.InstrumentationResultParser.reportResult(InstrumentationResultParser.java:461)
 	at com.android.ddmlib.testrunner.InstrumentationResultParser.parseStatusCode(InstrumentationResultParser.java:415)
 	at com.android.ddmlib.testrunner.InstrumentationResultParser.parse(InstrumentationResultParser.java:276)
 	at com.android.ddmlib.testrunner.InstrumentationResultParser.processNewLines(InstrumentationResultParser.java:247)
 	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
 	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
 	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
 	at com.android.ddmlib.Device.executeShellCommand(Device.java:615)
 	at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:259)
 	at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:285)
 	at com.squareup.spoon.SpoonDeviceRunner.main(SpoonDeviceRunner.java:533)

**Comment by LesterTheTester** [comment]
Here's something interesting in ddmlib's InstrumentationResultParser (Line 339).  Both errors and failures call the testFailed method...I wonder if we're getting one of each.  This also means spoon's "markTestAsError" is useless, there's no testErrored method on the Test Run Listener interface...it's not hooked up to anything anyway...

**Comment by edenman** [comment]
Ha, nice.  I wonder if the older versions of ddmlib had a separate `testErrored` callback or something.

Regardless, my fears about errantly marking the same method twice being an issue: do you by any chance have like a parameterized test runner or something?  It looks like the `com.android.ddmlib.testrunner.TestIdentifier` is just a className+methodName, which would mean a parameterized test would get results twice.

**Comment by LesterTheTester** [comment]
This is also pretty interesting, I get two unique testFailed messages:

[STRL.testFailed] test=com.yammer.droid.espresso.endtoend.GroupCreationE2ETest#CreatePublicGroup
[STRL.testFailed] failed java.lang.NullPointerException
[SDR.printStream] [emulator-5554] STDOUT at com.yammer.droid.resources.CompanyResourceProvider.getCompanyString(CompanyResourceProvider.java:36) .....blah blah blah this is our bug

and

[SDR.printStream] [emulator-5554] STDOUT 2016-08-08 21:41:09 [STRL.testEnded] test=com.yammer.droid.espresso.endtoend.GroupCreationE2ETest#CreatePublicGroup
[SDR.printStream] [emulator-5554] STDOUT 2016-08-08 21:41:09 [STRL.testFailed] test=com.yammer.droid.espresso.endtoend.GroupCreationE2ETest#CreatePublicGroup
STDOUT 2016-08-08 21:41:09 [STRL.testFailed] failed java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yammer.v1/com.yammer.droid.ui.group.GroupMembersAddActivity}: java.lang.NullPointerException

Very interesting the second failure comes in after a "testEnded"

**Comment by edenman** [comment]
Fun comment in InstrumentationResultParser, wrt the difference between fail/error:
```
            case StatusCodes.ERROR:
                // we're dealing with a legacy JUnit3 runner that still reports errors.
                // just report this as a failure, since thats what upstream JUnit4 does
                metrics = getAndResetTestMetrics();
                for (ITestRunListener listener : mTestListeners) {
                    listener.testFailed(testId, getTrace(testInfo));
                    listener.testEnded(testId, metrics);
                }

```

**Comment by LesterTheTester** [comment]
Nope...nothing funny going on like a parameterized test runner. Just a plain old espresso test and nothing else called GroupCreateE2ETest#CreatePublicGroup in the suite...

**Comment by LesterTheTester** [comment]
While I am also leary of the double marking, I wonder if causing the result parsing to totally fail is the desired approach. Definitely baffled us that according to the XML all our tests were "passing". Maybe we could log that a test is being double-marked and move on? Since there's no such thing as an error state, we can be assured that we're not losing any precision in the results.

**Comment by edenman** [comment]
Yeah, I'm guessing this is something that changed in ddmlib.  I'm just gonna merge your fix.

**Comment by edenman** [comment]
Just pushed this in 1.6.3, should be live in a couple hours.  Thanks again!
