### ISSUE TITLE
Error Merging Files

### ISSUE THREAD

**Issue by bagintz** [square/spoon#376]
On newest version (1.6.4)

Exception in thread "main" java.lang.RuntimeException: error while merging coverage files
	at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:232)
	at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:132)
	at com.squareup.spoon.SpoonRunner.main(SpoonRunner.java:694)
Caused by: java.io.IOException: Incompatible version 1007.
	at org.jacoco.core.data.ExecutionDataReader.readHeader(ExecutionDataReader.java:127)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:107)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:87)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:59)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:73)
	at com.squareup.spoon.SpoonCoverageMerger.mergeCoverageFiles(SpoonCoverageMerger.java:28)
	at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:229)

**Comment by bagintz** [comment]
I also got it on 1.6.2 when I went back.  The only other thing I noticed is that I had upgraded the gradle version in Android Studio

**Comment by ch-vadim-maximov** [comment]
+1 The same error after upgrading to the new Gradle version

**Comment by rzetzsche** [comment]
+1

**Comment by bagintz** [comment]
For what it is worth, it happens on Gradle 3.0 and Android gradle plugin 2.2.0-beta2 also

**Comment by edenman** [comment]
@bagintz @rzetzsche @ch-vadim-maximov thanks for reporting.  i don't have a project i can use to verify/fix this, unfortunately.  can one of you guys check out branch `edenman/bump-jacoco-version`, do a `mvn install` and then point your project at spoon version `1.6.5-SNAPSHOT` and see if it's fixed?

**Comment by bagintz** [comment]
Doing it now

**Comment by bagintz** [comment]
@edenman That seems to have worked!  I did not get a chance to test it on gradle <2.14.1, but it works on 2.14.1 for sure!

**Comment by bagintz** [comment]
@edenman I spoke too soon I think.  The coverage file does get constructed, but then I get an error when trying to send that file to Sonarqube

Incompatible execution data for class [class_name] with id [id]

A quick google seems that that error has to do with merging jococo files ??

**Comment by edenman** [comment]
thanks for checking @bagintz.  might've upgraded jacoco too far.  can you locally try changing to one of the intermediary versions and see which ones work?

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.jacoco%22%20AND%20a%3A%22jacoco-maven-plugin%22

**Comment by bagintz** [comment]
@edenman do you know how to find out, in a particular Android project, what version of jacoco they are using?

**Comment by edenman** [comment]
@bagintz nope :(

**Comment by originx** [comment]
JaCoCo was updated in Gradle 2.13 to 0.7.6
Fyi could be related: https://discuss.gradle.org/t/jacoco-coverage-for-android-test-cases-fails-in-gradle-version-2-13-and-2-14/18272/15

**Comment by bagintz** [comment]
@edenman ok, I changed my local "edenman/bump-jacoco-version" branch to use jacoco 0.7.6.201602180812, and then specified that version fo both the jacoco plugin and another one I was using to generate junit test coverage via jacoco (com.vanniktech.android.junit.jacoco).  After that, it all worked as expected.

**Comment by edenman** [comment]
@bagintz awesome, thanks.  mind submitting a PR?

**Comment by bagintz** [comment]
https://github.com/square/spoon/pull/385

**Comment by edenman** [comment]
Ok, just released this as 1.7.0.  Thanks again, @bagintz!

**Comment by bagintz** [comment]
Wonderful, thank you!!

**Comment by bagintz** [comment]
dumb question, but you updated your runner AND your client to 1.7.0?
