### ISSUE TITLE
Screenshots are all the same

### ISSUE THREAD

**Issue by sayoojvalsan-demandmedia** [square/spoon#384]
I used  Spoon.screenshot(mActivityRule.getActivity(), "after_login");

I am calling this in 3 different places in my Test. When I look into the images they all are same. 
The first screenshot is seen in all others.

Note : I am using espresso and getting activity using 
    @Rule
    public ActivityTestRule<WelcomeActivity> mActivityRule = new ActivityTestRule(WelcomeActivity.class);

**Comment by cmatulessy** [comment]
Hi sayoojvalsan-demandmedia, I see you closed this issue, but I have the same issue as you. Could you please share your solution how you solved this?

**Comment by Ahmed-H-Kamal** [comment]
I am also having the same issue, It will be a great help if you can clarify how did you solve this issue.

**Comment by cmatulessy** [comment]
Hi @Ahmed-H-Kamal 

I have the solution, you have this because .getActivity() get only your declared activity. So if you move from screen to screen you should make a method which is getting the current activity which is showing on the screen. Hereby my code implementation:

`public class ActivityFinder {
    private static Activity currentActivity;

    public static Activity getCurrentActivity() {

        getInstrumentation().runOnMainSync(new Runnable() {
            public void run() {
                Collection resumedActivities = ActivityLifecycleMonitorRegistry.getInstance().getActivitiesInStage(Stage.RESUMED);
                if (resumedActivities.iterator().hasNext()){
                    currentActivity = (Activity) resumedActivities.iterator().next();
                }
            }
        });

        return currentActivity;
    }

    private static Instrumentation getInstrumentation() {
        return InstrumentationRegistry.getInstrumentation();
    }


}
`

Hope this helps @Ahmed-H-Kamal

**Comment by Ahmed-H-Kamal** [comment]
Thanks a lot @cmatulessy you ROCKS 
It sure works as expected.
