### ISSUE TITLE
Screenshot of a dialog

### ISSUE THREAD

**Issue by adheesh24** [square/spoon#387]
Hi,

I have been trying to take the screenshot of the dialog but the screenshot of the activity gets captured.
I have gone through the previous posts and found that #4 issue is the only way to take the screenshot. I tried implementing it but found few difficulties in doing so. 
I wanted to know if there is an easy work around to take the screenshots of a dialog? I want the screenshot of my dialog to get created along with the other screenshots I take throughout my app.

Thanks,
Adheesh

**Comment by tir38** [comment]
Is Falcon not doing it for you?

**Comment by adheesh24** [comment]
Hi,
It initially didn't work out for me. So left it.. But tried implementing it again and it did work.
Thanks.
