### ISSUE TITLE
Overflow menu not visible on a screenshot

### ISSUE THREAD

**Issue by tomrozb** [square/spoon#388]
I don't know whether this is a bug or a feature, but overflow menu is not visible on a captured screenshot. I'm referring to the menu opened by the overflow button present on a Toolbar. 

I'd love to see overflow menu on screenshots, as it helps me compare if the UI matches mockups.

**Comment by JakeWharton** [comment]
PopupMenus show in separate windows. This is no different than a dialog or keyboard which also cannot be captured.

Try Falcon's spoon-compatible screenshot mechanism which uses some (dirty) reflection to capture every window in the process: https://github.com/jraska/Falcon

**Comment by JakeWharton** [comment]
Otherwise a dupe of #4.

**Comment by tomrozb** [comment]
@JakeWharton thanks, I'll give it a try!
