### ISSUE TITLE
Not able to integrate spoon-runner-1.7.0 with android studio

### ISSUE THREAD

**Issue by venkateshgowda** [square/spoon#390]
I am trying to generate test reports using spoon. Am using Espresso to write test cases for android application and spoon for generate test reports. I have followed each steps to integrate spoon with android studio. I failed when i added **spoon-runner-1.7.0-jar-with-dependencies.jar** to project it throws an error `Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_51\bin\java.exe'' finished with non-zero exit value 1
> `. If i removed that jar application compiles and execute properly. 
> Please help me out from this

**Comment by JakeWharton** [comment]
You can look at the test-app to see how we do this: https://github.com/square/spoon/blob/46aabef3c14bcc7d329c7f93496960d9f16db42f/test-app/build.gradle#L52-L78. There may be a Gradle plugin in the future.
