### ISSUE TITLE
Feature Request - Raw device log downloading

### ISSUE THREAD

**Issue by dmscheck** [square/spoon#391]
The HTML log files are nice, however there are use cases where the user may want to open the logs in an external program (i.e. editors, diff programs).  Can functionality be provided to keep the log files stored as text files in addition to HTML?  This can probably be off by default and enabled via a gradle flag.  Once the text files are saved, download buttons added to the HTML files would make downloading one or all tests in a ZIP file easy.

**Comment by edenman** [comment]
I'm open to this.  PRs welcome!
