### ISSUE TITLE
Unable to run for multiple devices

### ISSUE THREAD

**Issue by fleaman** [square/spoon#394]
I cannot run tests for two devices as a gradle task but spoon failed to run tests, works fine for one device though. I tried with two emulators, device and emulator, two devices. No difference.

It seems like java failed to start new processes to run test because it could not load google-collections for some reason.

Is there any idea what could be a problem here and how to make it work?

Environment:
OSX El Capitan 
java version "1.8.0_92"
Gradle version 2.14.1
spoon-gradle-plugin v1.2.2

Output:
tanfy.spoon.gradle.SpoonRunTask] ADB timeout 60000
18:30:59.737 [INFO] [com.stanfy.spoon.gradle.SpoonRunTask] Using all the attached devices
18:30:59.750 [QUIET] [system.out] 2016-10-18 18:30:59 [SR.runTests] Executing instrumentation suite on 2 device(s).
18:30:59.753 [QUIET] [system.out] 2016-10-18 18:30:59 [SR.runTests] Application: com.project.dev from /Users/project/espresso/android/app/build/outputs/apk/app-v11.4-b52-develop-debug.apk
18:30:59.753 [QUIET] [system.out] 2016-10-18 18:30:59 [SR.runTests] Instrumentation: com.project.tests from /Users/project/espresso/android/app/build/outputs/apk/app-develop-debug-androidTest-unaligned.apk
18:30:59.754 [QUIET] [system.out] 2016-10-18 18:30:59 [SR.runTests] [emulator-5554] Starting execution.
18:30:59.755 [QUIET] [system.out] 2016-10-18 18:30:59 [SR.runTests] [CVH7N15C21000940] Starting execution.
18:30:59.756 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.runInNewProcess] [CVH7N15C21000940]
18:30:59.756 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.runInNewProcess] [emulator-5554]
18:30:59.930 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR Error: A JNI error has occurred, please check your installation and try again
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR Error: A JNI error has occurred, please check your installation and try again
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at java.lang.Class.getDeclaredMethods0(Native Method)
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at java.lang.Class.getDeclaredMethods0(Native Method)
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at java.lang.Class.getMethod0(Class.java:3018)
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at java.lang.Class.getMethod0(Class.java:3018)
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at java.lang.Class.getMethod(Class.java:1784)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at java.lang.Class.getMethod(Class.java:1784)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
18:30:59.932 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
18:30:59.933 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [CVH7N15C21000940] STDERR       ... 7 more
18:30:59.933 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR  ... 7 more
18:30:59.933 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.runInNewProcess] Process.waitFor() finished for [CVH7N15C21000940] with exitCode 1
18:30:59.933 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.runInNewProcess] Process.waitFor() finished for [emulator-5554] with exitCode 1
18:30:59.933 [QUIET] [system.out] java.io.FileNotFoundException: /Users/project/espresso/android/app/build/spoon/develop/debug/work/emulator-5554/result.json (No such file or directory)
18:30:59.933 [QUIET] [system.out]       at java.io.FileInputStream.open0(Native Method)
18:30:59.933 [QUIET] [system.out]       at java.io.FileInputStream.open(FileInputStream.java:195)
18:30:59.933 [QUIET] [system.out]       at java.io.FileInputStream.<init>(FileInputStream.java:138)
18:30:59.933 [QUIET] [system.out]       at java.io.FileReader.<init>(FileReader.java:72)
18:30:59.933 [QUIET] [system.out]       at com.squareup.spoon.SpoonDeviceRunner.runInNewProcess(SpoonDeviceRunner.java:152)
18:30:59.933 [QUIET] [system.out]       at com.squareup.spoon.SpoonRunner$1.run(SpoonRunner.java:198)
18:30:59.933 [QUIET] [system.out]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
18:30:59.933 [QUIET] [system.out]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
18:30:59.933 [QUIET] [system.out]       at java.lang.Thread.run(Thread.java:745)
18:30:59.933 [QUIET] [system.out] java.io.FileNotFoundException: /Users/project/espresso/android/app/build/spoon/develop/debug/work/CVH7N15C21000940/result.json (No such file or directory)
18:30:59.933 [QUIET] [system.out]       at java.io.FileInputStream.open0(Native Method)
18:30:59.933 [QUIET] [system.out]       at java.io.FileInputStream.open(FileInputStream.java:195)
18:30:59.934 [QUIET] [system.out]       at java.io.FileInputStream.<init>(FileInputStream.java:138)
18:30:59.934 [QUIET] [system.out]       at java.io.FileReader.<init>(FileReader.java:72)
18:30:59.934 [QUIET] [system.out]       at com.squareup.spoon.SpoonDeviceRunner.runInNewProcess(SpoonDeviceRunner.java:152)
18:30:59.934 [QUIET] [system.out]       at com.squareup.spoon.SpoonRunner$1.run(SpoonRunner.java:198)
18:30:59.934 [QUIET] [system.out]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
18:30:59.934 [QUIET] [system.out]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
18:30:59.934 [QUIET] [system.out]       at java.lang.Thread.run(Thread.java:745)
18:30:59.936 [QUIET] [system.out] 2016-10-18 18:30:59 [SR$1.run] [emulator-5554] Execution done. (0 remaining [])
18:30:59.936 [QUIET] [system.out] 2016-10-18 18:30:59 [SR$1.run] [CVH7N15C21000940] Execution done. (0 remaining [])

**Comment by tir38** [comment]
So you're saying that you don't get this error when you run spoon on only one device?

`
18:30:59.931 [QUIET] [system.out] 2016-10-18 18:30:59 [SDR.printStream] [emulator-5554] STDERR Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
`

**Comment by fleaman** [comment]
that's right, it happens only when I have more than one device/emulator connected.

**Comment by tir38** [comment]
Do you see the problem when multiple devices are connected and running tests  outside spoon. i.e. `.gradlew connectedAndroidTest` ?

**Comment by fleaman** [comment]
then it works fine when I run tests from command line, like this:
java -jar spoon-runner-1.3.1-jar-with-dependencies.jar ...

**Comment by fleaman** [comment]
The problem is solved
The reason was that the module 'guava' was excluded in gradle file

classpath('com.stanfy.spoon:spoon-gradle-plugin:1.2.2') {
       exclude module: 'guava'
}

fixed when I changed it to 
classpath('com.stanfy.spoon:spoon-gradle-plugin:1.2.2')
