### ISSUE TITLE
Question: Does Spoon take screenshots in setup / teardown methods?

### ISSUE THREAD

**Issue by tir38** [square/spoon#396]
I've got Spoon successfully taking screenshots during tests. I just noticed that i'm not getting any screenshots in my reports if I try to capture during `@Before` and `@After` annotated methods.

Is this something that Spoon should be doing and I'm just not doing it correctly. Or is this not (yet) a feature?

**Comment by JakeWharton** [comment]
The method under test can't be detected. We should switch to a TestRule
instead.

**Comment by tir38** [comment]
You say "should switch"... so what is it doing now?

**Comment by JakeWharton** [comment]
Stacktrace introspection.

**Comment by JakeWharton** [comment]
Test rule is on master.
