### ISSUE TITLE
Use a test rule for screenshot capturing.

### ISSUE THREAD

**Issue by ericharlow** [square/spoon#401]
This provides access to the class name and method name without reflection.

----

**Original issue:**

My scenario is I would like to be able to save a custom test log file in the @After of a test base class. I am fine with managing getting the name of the subclass and method name until there is an alternative way of detecting class name and method name like mentioned in #396.  

All that is needed to make this happen is to change the scope of 
`private static File save(Context context, String className, String methodName, File file)`.

pr #400

**Comment by JakeWharton** [comment]
That would be a very bad API to expose.

Instead we're going to write a test rule which is a superior mechanism for accessing the test name. I'm going to repurpose your issue to track that.

**Comment by JakeWharton** [comment]
This happened on `master`.

**Comment by Skylive** [comment]
Hello,

My scenario is the same as the first message.
I saw that you made changes for the `screenshot()` method in a SpoonRule (which is a great thing) in `master` but the `save()` method seems to be missing.
