### ISSUE TITLE
Can this be used with appium ?

### ISSUE THREAD

**Issue by vikramvi** [square/spoon#406]
Hi,

Please clarify if I can use this framework with appium automated cases ?

Thanks & Regards,
Vikram

**Comment by JakeWharton** [comment]
If appium is just a library then yes. Spoon is an instrumentation runner so all it cares about is that you have a real APK and a test APK and then it just asks Android to run the tests. As to what libraries and tools you use inside the test APK, Spoon is completely agnostic to.
