### ISSUE TITLE
Google map is blank on screenshots

### ISSUE THREAD

**Issue by ch-vadim-maximov** [square/spoon#407]
Hello,
For some reason map is not captured by the screenshots.
![mapnotvisible](https://cloud.githubusercontent.com/assets/19157795/21245805/8b9dca1e-c2d9-11e6-8602-2861b6383e76.png)
Is there a setting I'm missing or this is a limitation of the screenshot library?

Thanks!

**Comment by JakeWharton** [comment]
Google Maps is a hole punched through your application and rendered in GL. This will be solved with #4. For now use Falcon's spoon-compat library to capture screenshots: https://github.com/jraska/Falcon

**Comment by dthommes** [comment]
Just to let you know: Falcon does not solve the problem with Maps. It probably cannot handle OpenGL as well.
