### ISSUE TITLE
How to get standard XML junit output with spoon

### ISSUE THREAD

**Issue by tandroidt** [square/spoon#409]
Hi!
How can I get a standard XML junit output when using spoon?
I saw in Issue #100 ( square/spoon#100) that you added this option, but couldn't find out how to use it or to where it is generated.
I want to use the xml output in JIRA.

I run it on a real device, with jenkins.
Do I need to use any special flag to make spoon crate the xml?
right now I run it with these command :

java -jar $SPOON_JAR --apk $APK_PATH --test-apk $TEST_APK_PATH --output $SPOON_REPORT_PATH --title "$TITLE" --class-name $TEST_SUITE_CLASS

Do I need to add anything?

Thanks!

**Comment by edenman** [comment]
it goes in the `junit-reports` folder

**Comment by tandroidt** [comment]
Do you know what is the full path of this folder ?and is it generated by default ?
I only find the "build/spoon-output" and inside is the index.html report.

Thanks!

**Comment by edenman** [comment]
it does seem to be generated by default.  the file is generated on-device, afaict.  you'll have to poke around and find it, i don't have a project up at the moment that is using Spoon.

**Comment by tandroidt** [comment]
There is not folder with this name on the device or on the slave =/
Any other ideas ?
