### ISSUE TITLE
Need the ability to pick up application apk with classifier

### ISSUE THREAD

**Issue by hqfking** [square/spoon#410]
Maven workflow:

Now, if I specify the classifier with the application apk dependency, it has no effect at all. 

For example, I want to pick the exampleapp-1.0-debug.apk as the application apk to test.  I can specify the debug as the classifier in the dependency.  However, spoon still only looks for exampleapp-1.0.apk

**Comment by JakeWharton** [comment]
The Maven plugin has been removed in the next major release. You'll have to either use a plugin that allows you to execute a Java main method, shell out to the uber jar, or use Spoon outside of Maven.
