### ISSUE TITLE
How to ignore test failures but fail if no device connected

### ISSUE THREAD

**Issue by hram** [square/spoon#412]
I run tests on CI
I need notify users if no devise connected
But don't need notify users if tests failures

How can I do that?

**Comment by LesterTheTester** [comment]
In a step before running tests, I'd parse the output of 'adb devices' to see if any devices are connected.

**Comment by JakeWharton** [comment]
By default, on `master`, the build will fail if no devices are connected and it will also fail if a test fails. You can specify `--always-zero` now so that even if the run fails the return code will be zero, but if no devices are connected it will still fail.
