### ISSUE TITLE
Feature Request: Customizing Success / Failure Colors

### ISSUE THREAD

**Issue by NickCapurso** [square/spoon#414]
My team has a scenario where we would like to color the Spoon output differently for specific tests. 

For example, tests annotated with `@FlakyTest` (Android) should be colored differently in the Spoon output if they fail (a related secondary feature might be excluding certain tests from contributing to overall success/failure via `SpoonRunner#parseOverallSuccess`). Currently, we're just excluding these tests from running on Spoon, so it's easy to lose visibility of them.

I've played with a source to enable this at a per-test level, where the test name / color is explicitly named:
`--customTestFailureColors "testEmptyForm_ShowsBothErrors:#4343ba" "testMakeASandwich_ItTastesGood:#a3139d" "testMakeSomeSalad_ItIsHealthy:#ecee1a"`
<img width="1205" alt="screen shot 2017-01-21 at 6 20 39 pm" src="https://cloud.githubusercontent.com/assets/5898509/22406529/b6527ed2-e622-11e6-8e4c-4e7784bae8b8.png">

I'm continuing to work on this problem for fun and can make a PR at some point, if there's interest.

Ideally, it'd be great to do it based on annotations, but from poking around the codebase, I don't see that Spoon has access to the actual annotations (ex. through the `RemoteTestRunner`). 

It should be able for this to be done on a per test / class / package level and a quick-and-dirty way to do annotation-level would be for the Spoon user to build up a list of tests with the desired annotation by parsing source files using `grep` or something similar.

**Comment by edenman** [comment]
Sounds like a pretty fringe usecase, so I don't think we'd want to support this.  Feel free to fork!
