### ISSUE TITLE
Context in spoon.save()

### ISSUE THREAD

**Issue by Galileo1** [square/spoon#425]
what does context in spoon.save() mean?How can I get it in espresso testcase??

**Comment by JakeWharton** [comment]
Use the activity rule to get the activity under test, or `InstrumentationRegistry.getTargetContext()`.

**Comment by Galileo1** [comment]
thanks @Jake Wharton. I am trying to use the same but seems like it is not attaching the files for the testcase in report .This is what I have been doing Spoon.save(InstrumentationRegistry.getTargetContext() ,new File(getExternalStorageDirectory(), app_log)). Trying to attach all the files in app_log folder. But this does work???
