### ISSUE TITLE
change screen orientation and take screenshot of activity

### ISSUE THREAD

**Issue by Galileo1** [square/spoon#429]
Haven't got any answers here so have to put it up in this issue- [http://stackoverflow.com/questions/42802441/android-espresso-change-screen-orientation-and-take-screen-shot-of-activity](url)

**Comment by JakeWharton** [comment]
Call requestOrientation on the activity before calling for a screenshot.

**Comment by Galileo1** [comment]
@JakeWharton that doesn't work  for some. I am already  changing the orientation of the screen using this code  and getting portrait screenshot `  final Activity activity = (Activity) view.getContext();   activity.setRequestedOrientation(orientation);
        Collection<Activity> resumedActivities = ActivityLifecycleMonitorRegistry.getInstance().getActivitiesInStage(Stage.RESUMED);
        if (resumedActivities.isEmpty()) {
            throw new RuntimeException("Could not change orientation");
        }`

**Comment by JakeWharton** [comment]
I don't know then. This isn't specific to Spoon so StackOverflow is a
better place to ask.
