### ISSUE TITLE
How to build locally for testing?

### ISSUE THREAD

**Issue by BootComp** [square/spoon#431]
Hi,
Could you please point me to some documentation to show how to build this spoon JAR (snapshot / release) locally so I can try using that (for a wannabe contributor)?

The JAR built with `./gradlew build` or `./gradlew install` or `./gradlew shadowJar` etc.. do not work. I see an error of `no main manifest attribute, in spoon-runner/build/libs/spoon-runner-2.0.0-SNAPSHOT.jar` with that.

**Comment by JakeWharton** [comment]
./gradlew build

**Comment by BootComp** [comment]
I did try that but it looks like the spoon-runner JAR created with that does not work :(
I see an `no main manifest attribute, in spoon-runner/build/libs/spoon-runner-2.0.0-SNAPSHOT.jar` error when trying.

**Comment by BootComp** [comment]
I'm probably missing something basic, but would be cool to know how to build a JAR that works when trying to run locally (without the manifest error). Have tried `./gradlew build / install/ shadowJar` etc.. so far

**Comment by edenman** [comment]
`./gradlew clean build` is what I use to make a release, so i'm reasonably certain it's outputting the correct thing.  how are you invoking the resulting spoon-runner JAR?

**Comment by BootComp** [comment]
`java -jar spoon-runner/build/libs/spoon-runner-2.0.0-SNAPSHOT.jar --apk` ....

**Comment by edenman** [comment]
sorry, I got this project mixed up with android-times-square.  I haven't done a release since we switched to gradle, i bet there's something screwed up in the jar it produces.  @BootComp while we figure this out, you can go back to 092068b80191c4e33f5432f7635ca547141e28d0 and run `mvn install`

**Comment by BootComp** [comment]
thanks. gave that a try as well but got an
`[ERROR] The goal you specified requires a project to execute but there is no POM in this directory`

**Comment by edenman** [comment]
@BootComp Just worked for me in the project root.  maven 3.3.9, fwiw.

**Comment by BootComp** [comment]
Indeed that does work (was in the wrong branch 🤦‍♂️ ).Thanks @edenman
