### ISSUE TITLE
fail-on-failure returns non-zero exit code only if at least half of the devices failed

### ISSUE THREAD

**Issue by tandroidt** [square/spoon#455]
When running spoon on out CI server, I see that if there are more than two devices connected, the exit code returned is according to the result of the last device in spoon report list.
I need it to return **non-exit code if at least one of the devices failed** in the tests. is it possible ?

Thanks!

**Comment by edenman** [comment]
hm, that's weird.  the work that Jake is doing on master should fix this, he's changing a bunch of stuff around exit codes

**Comment by tandroidt** [comment]
Ok great, when should it be ready so ill check if it works after the changes? 

Thanks a lot!!

**Comment by tandroidt** [comment]
Thanks! when the version is planned to be out ?

**Comment by edenman** [comment]
@tandroidt I don't think we have an estimate at the moment, sorry
