### ISSUE TITLE
Run each test in its own instrumentation process using dex-test-parser

### ISSUE THREAD

**Issue by kirillzh** [square/spoon#463]
https://github.com/linkedin/dex-test-parser

**Comment by JakeWharton** [comment]
We already do this using a vastly superior mechanism than parsing: https://github.com/square/spoon/pull/456.

**Comment by kirillzh** [comment]
I didn't know you already do that... So then my question is why does the whole test run is getting interrupted by crashed target application or instrumentation?

**Comment by JakeWharton** [comment]
It's not released yet
