### ISSUE TITLE
third-party/axmlparser is unable to parse AndroidTest APKs built by Android Studio 3

### ISSUE THREAD

**Issue by MonteCreasor** [square/spoon#468]
The com.squareup.spoon.internal.thirdparty.axmlparser.AXMLParser fails to extract the test package, app package, and test runner class from any instrumentation test APKs built with Android Studio 3 Canary 2, 3, or 4. The checkNotNull statements in the runner's InstrumentationInfo.parseFromFile() method

            checkNotNull(testPackage, "Could not find test application package.");
            checkNotNull(appPackage, "Could not find application package.");
            checkNotNull(testRunnerClass, "Could not find test runner class.");

all fail because AXMLParser is unable to read the Manifest entries from the test APK.

I tried to figure out why AXMLParser was failing but was unsuccessful so my workaround was to replace axmlparser with https://github.com/clearthesky/apk-parser (package name package net.dongliu.apk.parser) which is able to parse these APKs successfully. Since apk-parser did not have code to parse the "instrumentation" meta info (required by the spoon runner), I added the following case statement to net.dongliu.apk.parser.parser.ApkMetaTranslator:

            case "instrumentation":
                apkMeta.setInstrumentationName(attributes.get("name"));
                apkMeta.setInstrumentationLabel(attributes.get("label"));
                apkMeta.setTargetPackage(attributes.get("targetPackage"));
                break;
This works but the problem is that the apk-parse package is huge and is overkill as a replacement for axmlparser. So I'm hoping you might look into this issue and figure out why axmlparser fails.

**Comment by MonteCreasor** [comment]
OK, I figured it out. 

The problem is that axmlparser assumes that the compiled strings in the manifest are 2 bytes and therefore getRaw() calls getShort() for each character it expects to read. That works for APKs compiled using pre-Android Studio 3 build tools. Android Studio 3 compiles the manifest strings using 1 byte per character and that's what is preventing axmlparser from being able to pull out the strings.

There is likely a value in the compiled manifest header that specifies whether the strings are stored in 2 byte unicode or as single bytes, but unfortunately, I don't know enough about the structure of the manifest to know the offset where this information is stored. 

I suppose I could use the length of the first string (which precedes the string) and check if there is a null (00) at length * 1 bytes or at length * 2 bytes, but that would be kind of kludgy.

**Comment by JakeWharton** [comment]
Let me ask someone if there's an indicator byte. I suspect it's UTF-8 vs
UTF-16.

**Comment by MonteCreasor** [comment]
Thanks. When you find out, I can fix up the parser to handle both cases. It'll be a bit tricky though because the data structures being passed around everywhere ar int[] arrays and they should probably by byte[] arrays; it would make the code simpler.

**Comment by JakeWharton** [comment]
Can you upload a manifest somewhere that has these 1-byte strings?

**Comment by MonteCreasor** [comment]
Sure, just a sec. I have one open in vi which I'm using in hex mode (:%!xxd). That's how I discovered the UTF-8. I'll send you a Dropbox link.

**Comment by JakeWharton** [comment]
I think this is a result of aapt2 being turned on by default starting in
one of the alphas. Looks like there's a flag in the header of the string
pool which indicates when the contents are UTF-8:
https://android.googlesource.com/platform/frameworks/base/+/master/libs/androidfw/include/androidfw/ResourceTypes.h#452.
It's been there forever, but it seems like it was never being used (on the
manifest, at least).

**Comment by MonteCreasor** [comment]
[a3.zip](https://github.com/square/spoon/files/1150838/a3.zip)

Here's the example Android Studio 3 compiled manifest that uses UTF-8. I extracted it from my test APK. And here is the same manifest file compiled using Android Studio 2.3.2 with UTF-16.

[a2.zip](https://github.com/square/spoon/files/1150841/a2.zip)

**Comment by MonteCreasor** [comment]
Here are 2 PNGs that might save you some time.

Here is a PNG of the UTF-16 (Android Studio 2) manifest in my vi editor:

![a2](https://user-images.githubusercontent.com/5382350/28244738-1d84f982-69c1-11e7-83b0-f02693946392.png)

Here is a PNG of the UTF-8 (Android Studio 3) manifest:

![a3](https://user-images.githubusercontent.com/5382350/28244739-1faaba76-69c1-11e7-8710-c5c324117671.png)

**Comment by MonteCreasor** [comment]
Ya, I just figured out myself by checking out the int value that was read but never used (the one with the /*?*/) marker...

        ReadUtil.readCheckType(reader,CHUNK_TYPE);
        int chunkSize=reader.readInt();
        int stringCount=reader.readInt();
        int styleOffsetCount=reader.readInt();
        /*?*/reader.readInt();
        int stringsOffset=reader.readInt();
        int stylesOffset=reader.readInt();

it's 0 on the UTF-16 version and 256 on the UTF-8 version. I was just guessing that it might be the value I was looking for so I checked it out in the debugger.

**Comment by JakeWharton** [comment]
Yep if you follow the link above the UTF-8 constant is defined as 1<<8. So
it looks like we have enough information to handle the UTF-8 case! Do you
want to send a PR? If not I can take a look this week.

**Comment by MonteCreasor** [comment]
I'm less busy than you, so I'll send a PR once I've got it working and tested with both string formats.

**Comment by JakeWharton** [comment]
What're you talking about? I'm unemployed now!

**Comment by MonteCreasor** [comment]
Well that won't last long! 

I've fixed the code and I tried to change as little as possible so that it would be easier for you to see what was really added or changed. I resisted the temptation to rip out the guts and leave only the small bit of functionality that you actually require for Spoon.  Most of it is fluff and not used.

The UTF-8 format is kind of odd. The string length field at precedes each string is supposed to be a single byte unless it's a really long string, in which case, 2 bytes (chars) are used for the length. In the APK I've been testing, each length actual uses 2 bytes and they are duplicates of each other. For example, a string of length 5 will have the following length in hex 0505 and a string of length 7 will have 0707. Weird eh? I just advance over the second repetitive byte to get to the actual string start. 

I used a ByteBuffer to simplify all the pointer arithmetic and I added a full set of JUnit test along with 2 mock APKs (UTF-8 and UTF-16) that you can run to verify that parsing works for both cases.

I only seem to be able to run the tests by right clicking on the test directory and clicking 'run all tests'. When I do it form the command line using

     ./gradlew third-party:axmlparser:test, 

my test code will not find the location of the 2 test APKs that are used as input for the test. Sorry about that. 

One final note. I set my ByteBuffer with order(ByteOrder.BIG_ENDIAN) although all my reading says that is should be LITTLE_ENDIAN, But the BIG_ENDIAN works perfectly when using the ByteBuffer, and when I tried to use LITTLE_ENDIAN, the characters came out with their bytes flipped.  That results in the text looking like a string of Chinese symbols which is interesting, but not too useful.

I'll do a PR now.
