### ISSUE TITLE
Store screenshot storage issue when running on 3rd Party device grid 

### ISSUE THREAD

**Issue by KaurManjot** [square/spoon#471]
I run my tests on android app that capture spoon screen shot in espresso. Read about permission issues and already added

to the debug manifest

All our tests are run on 3rd part device grid(Perfecto) where it throw error: Caused by: java.lang.IllegalAccessException: Unable to create output dir: /storage/emulated/0/app_spoon-screenshots

Locally saw this error and was able to fix by enabling storage permission Settings>Apps>Manage Apps>Permissions>enable storage

But on 3rd party grid app is installed every time (available device is acquired)so the storage setting is lost.

Is there a way to make this persist or some other way like I can enable before running test etc.
Tests are running on Galaxy S6 6.0.1 but can run on latest devices as well.

Can spoon use internal storage for screenshots? I faced this issue on emulator and read on of the post to create sdcard and start emulator with sdcard, resolved that ... now on real device which we don't have much control ... then storage is lost after app is uninstalled (mostly, until app have some extra logic) .. Isn't it better is spoon can make changes to use internal storage? or some other persistent place

**Comment by JakeWharton** [comment]
We can't pull files off of internal storage if memory serves.

**Comment by KaurManjot** [comment]
I think this issue can be closed. Alternatives I found:
https://stackoverflow.com/questions/32787234/how-to-manage-runtime-permissions-android-marshmallow-espresso-tests

**Comment by JakeWharton** [comment]
Great!
