### ISSUE TITLE
[Feature request] Retry policies

### ISSUE THREAD

**Issue by caipivara** [square/spoon#476]
Hi

Sometimes installation of the apks on the test devices may fail with something like:

```
09:02:54 D/app-debug.apk: Uploading app-debug.apk onto device '00c572fedbd7a1ca'
09:02:54 D/Device: Uploading file onto device '00c572fedbd7a1ca'
2017-09-14 09:02:56 [SDR.run] InstallException while install app apk on device [00c572fedbd7a1ca]
com.android.ddmlib.InstallException: Unknown failure (Error: Can't open non-file: /data/local/tmp/app-debug.apk)
```

It will be cool to have a retry policy here to avoid having to recompile or rerun your CI job in order to pass. 

Ideas:
- Retry 3 times waiting 300 ms.
- Retry just if installation failed.

**Comment by jaredsburrows** [comment]
This might be a duplicate of https://github.com/square/spoon/issues/101.

**Comment by edenman** [comment]
Yup, thanks @jaredsburrows
