### ISSUE TITLE
How to build executable spoon-runner jar from source?

### ISSUE THREAD

**Issue by ch-vadim-maximov** [square/spoon#479]
Given this issue https://github.com/square/spoon/pull/477, I've been trying to build from source.
So far any jars that I was able to generate don't work. How is spoon-runner-1.7.0-jar-with-dependencies.jar gets generated?

**Comment by JakeWharton** [comment]
`./gradlew build`

**Comment by ch-vadim-maximov** [comment]
@JakeWharton Thanks for the reply. I tried that. And I assume the `spoon-runner/build/lib/spoon-runner-2.0.0-SNAPSHOT-all.jar` should work, but I get this error:

`spoon-runner: unrecognized option '--fail-if-no-device-connected'`

**Comment by JakeWharton** [comment]
Try --help. We changed a bunch of option names for 2.0.

**Comment by edenman** [comment]
In particular, `--fail-if-no-device-connected` is now the default behavior
