### ISSUE TITLE
Disable Autofill setting for Android Oreo (sdk 26)

### ISSUE THREAD

**Issue by caipivara** [square/spoon#487]
If you run tests on a test device with Android Oreo, autofill dialogs are presented just after every textfield is selected causing the tests to fail.

It will be cool to have a feature like `--no-animations` but for Autofill, mayme `--no-autofill` that disable this on any test device.

**Comment by edenman** [comment]
Sorry, this is not a Spoon issue.

**Comment by caipivara** [comment]
Yeah, it's not an issue, it's a feature request. 

It should solve what `--grant-all` solved for sdk 21.
