### ISSUE TITLE
Access to original low-level AST

### ISSUE THREAD

**Issue by Egor18** [square/spoon#488]
Hello. I was playing around with spoon to perform some simple analysis.
And my question is: Is it possible to get the original low-level AST, which exists before AST simplification?

Let me explain it with a simple example. Here is the original code:
```
if (cond)
  return ((((10))));
else return 20;
```

And here is the same code after AST simplification:
```
if (cond)
{
  return 10;
}
else
{ 
  return 20;
}
```

So in spoon we are working only with the simplified code. But can I somehow lookup for the original AST?
Can I find these unnecessary parentheses in the AST?

---
Also I probably have found some issue with `getPosition()` method.
Consider the following code:
```
if (cond) return 10;
else return 20;
```

When I'm trying to get positions this way:
```
@Override
public void visitCtIf(CtIf ifElement)
{
  super.visitCtIf(ifElement);
  
  CtStatement thenStatement = ifElement.getThenStatement();
  CtStatement elseStatement = ifElement.getElseStatement();
 
  System.out.println(thenStatement.getPosition());
  System.out.println(elseStatement.getPosition());

  ...
}
```

It outputs:
```
(unknown file)
(unknown file)
```

But if I change source code to this:
```
if (cond)
{
  return 10;
}
else
{
  return 20;
}
```

It works fine:
```
(/Users/Egor/eclipse-workspace/Test/src/Test.java:10)
(/Users/Egor/eclipse-workspace/Test/src/Test.java:14)
```

To bypass this issue I have to use this trick:
```
SourcePosition thenPos = thenBody.getStatement(0).getPosition();
SourcePosition elsePos = elseBody.getStatement(0).getPosition();
```

It would be great to have it fixed :)
Thank you.

**Comment by JakeWharton** [comment]
Wrong Spoon project! You want https://github.com/INRIA/spoon

**Comment by Egor18** [comment]
Oh. I'm sorry.

**Comment by JakeWharton** [comment]
No problem!
