### ISSUE TITLE
[2.0.0-SNAPSHOT] - Junit reports seem to not be genereated

### ISSUE THREAD

**Issue by jaredsburrows** [square/spoon#498]
All tests run but junit reports are not generated.

## 1.7.1
<img width="274" alt="screen shot 2017-11-15 at 4 05 34 pm" src="https://user-images.githubusercontent.com/1739848/32866935-0cee4af6-ca1f-11e7-8205-b8896311beee.png">

## 2.0.0-SNAPSHOT
<img width="266" alt="screen shot 2017-11-15 at 4 05 25 pm" src="https://user-images.githubusercontent.com/1739848/32866936-10a40ffa-ca1f-11e7-87fb-2f6ba1c2277b.png">

**Comment by jaredsburrows** [comment]
This is really bad because we do not know which tests would have failed on the CI.

**Comment by idulkin** [comment]
I'm encountering this issue as well. I believe it's related to test orchestrator. Because each test runs as its own instrumentation, Spoon is creating an xml report after each test, and overwriting the previous report for that device. So we only get the output of the last test to run on each device.

**Comment by jaredsburrows** [comment]
@idulkin I do believe you are right, it seems to only save the "last" test because it keeps overriding the junit xml report, so there is only 1 test listed.

How can we force spoon to not run like this? Maybe using this new option, we can run all the tests together again? https://github.com/square/spoon/commit/53a63fe4a5182773a05c21c8c494cf754c793bf3#diff-2a33694ea19ca0cbba8207fda7dcfbd6R73

**Comment by jaredsburrows** [comment]
@idulkin Can you try using `--single-instrumentation-call`?

**Comment by idulkin** [comment]
@jaredsburrows I was just about to try that! I'm concerned about a single instrumentation losing Test Orchestrator's ability to isolate crashes, but let's see what happens.

**Comment by jaredsburrows** [comment]
Yes, it seems to bring the junit reports back but the test are no longer isolated. This means that the CI cannot report back which tests failed unless you fail the build on the first failed test.

**Comment by idulkin** [comment]
I think the real problem isn't with Spoon, but with the (XmlTestRunListener)[https://android.googlesource.com/platform/tools/base/+/tools_r22/ddmlib/src/main/java/com/android/ddmlib/testrunner/XmlTestRunListener.java] from ddmlib. When each instrumentation finishes, testRunEnded is called and a report is generated. It seems like we would need a completely different run listener to handle multiple instrumentations per test suite.

**Comment by edamyanov** [comment]
I think this [https://github.com/square/spoon/pull/519](519) fixes this problem.

**Comment by tobi512** [comment]
@jaredsburrows The fix of Emanuil looks good, would be great to have a quick merge here, since the broken reports currently block us a little bit...

**Comment by jaredsburrows** [comment]
@tobi512 It needs to be merged here first. I am not an owner or collaborator of this repo.

**Comment by edenman** [comment]
should be fixed on master now, sorry for the delay.
