### ISSUE TITLE
Skip quering active tests if singleInstrumentationCall=true

### ISSUE THREAD

**Issue by lsuski** [square/spoon#504]
According to source code of SpoonDeviceRunner quering active tests (running `adb shell am instrument log`)  is only useful if `singleInstrumentationCall=false`. Depending on number of tests and framework used it can take some time which is unnecessary

**Comment by JakeWharton** [comment]
Want to send a PR?

**Comment by lsuski** [comment]
No problem

**Comment by lsuski** [comment]
Actually, there is a problem :), because Spoon still needs runName and testCount. I'll try to figure out how to obtain these values without running through all tests

**Comment by lsuski** [comment]
I don't think it is possible to obtain number of tests and run name in different way so this can be closed.
