### ISSUE TITLE
[Feature request] Running tests from a shard in a single instrumentation

### ISSUE THREAD

**Issue by edamyanov** [square/spoon#509]
In Spoon 2.x every test is run in a separate instrumentation call.  When using sharding this has increased significantly the time for which tests are executed. Recently --single-instrumentation-call flag has been added but it runs all tests in a single instrumentation. I could not find an option to run only tests from a particular shard in a single instrumentation call.
Have you considered adding such an option so that only tests from a particular shard to be executed in a single instrumentation call (as it used to be with Spoon 1.x)?

**Comment by JakeWharton** [comment]
Sounds good. Want to send a PR?

**Comment by edamyanov** [comment]
Yes, with pleasure!

**Comment by edamyanov** [comment]
I created a PR for this issue but as I see @tchernykh has made another :)

**Comment by jaredsburrows** [comment]
@edamyanov Will this solve the problem?
 - with out specifying `singleInstrumentationCall = true` - all reports are clobbered
 - specifying `singleInstrumentationCall = true` - no reports

**Comment by edamyanov** [comment]
@jaredsburrows Unfortunately not but I will take a look if I can fix it.

**Comment by edenman** [comment]
Should be fixed, lmk if not
