### ISSUE TITLE
Base Class Tests

### ISSUE THREAD

**Issue by f2prateek** [square/spoon#54]
If I have a [base class](https://github.com/f2prateek/FoodBot/blob/test-spoon/integration-tests/src/main/java/com/f2prateek/foodbot/test/ActivityTest.java) for my tests, screenshots don't work. [This](https://github.com/f2prateek/FoodBot/blob/test-spoon/test-output.tiff) is how the spoon dashboard looks.
The same test suite does work if I remove the [testActivityIsCreated()](https://github.com/f2prateek/FoodBot/blob/test-spoon/integration-tests/src/main/java/com/f2prateek/foodbot/test/ActivityTest.java#testActivityIsCreated) method.

To try it out, you can check out [this branch](https://github.com/f2prateek/FoodBot/tree/test-spoon) and run test-cli.sh (handles building the app and tests).

```
java.lang.NullPointerException
 at com.square.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:225)
 at com.square.spoon.SpoonRunner.runTests(SpoonRunner.java:110)
 at com.square.spoon.SpoonRunner.run(SpoonRunner.java:78)
 at com.square.spoon.SpoonRunner.main(SpoonRunner.java:365)
```

**Comment by edenman** [comment]
In 1.1.4 you can now pass in the test class/method names manually, which you should do if you're screenshot things from a base class.
