### ISSUE TITLE
removing -r argument from am instrument

### ISSUE THREAD

**Issue by technomark** [square/spoon#549]
On our CI we see lots of lines like

> ▸ 08:55:53 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: numtests=113

I found if I removed -r from `am instruments` they go away.  How can I impose this on Spoon?

**Comment by edenman** [comment]
afaict that's not configurable :/

https://android.googlesource.com/platform/development/+/ac2a8469f27968904243b98d1546a12825178a11/tools/ddms/libs/ddmlib/src/com/android/ddmlib/testrunner/RemoteAndroidTestRunner.java#215

**Comment by edenman** [comment]
(feel free to reopen if you figure out a way)
