### ISSUE TITLE
How to read merged-coverage.ec

### ISSUE THREAD

**Issue by jihunim** [square/spoon#556]
I generated merged-coverage.ec but I don't know how to read it.
Could you tell me how to read it or is there a way to read it with jacoco?

**Comment by dagerler001** [comment]
> I generated merged-coverage.ec but I don't know how to read it.
> Could you tell me how to read it or is there a way to read it with jacoco?

I also encountered this problem and I found a solution

Add this gradle task in project 
https://gist.github.com/dagerler001/771418e0e12b109e23450fd45e767db1

` apply from: 'jacoco.gradle' ` insert it in your **build.gradle** (app)

I hope it's help you.

**Comment by jihunim** [comment]
Thank you. I helped me solving the problem.
