### ISSUE TITLE
Spoon for iOS

### ISSUE THREAD

**Issue by renasti** [square/spoon#561]
Hi.
Is it possible to use Spoon to test iOS devices?

**Comment by JakeWharton** [comment]
No, it is extremely Android-specific. In theory you could create a different frontend for running tests on iOS and generate a model that matches what Spoon uses. Then you could generate the HTML report using Spoon based on that model. This is already how it works internally. The report generation knows nothing about Android. But we have nothing like that built in and aren't going to provide it ourselves.

**Comment by edenman** [comment]
Nope
