### ISSUE TITLE
Spoon#copy causes a buffer overrun

### ISSUE THREAD

**Issue by sunyal** [square/spoon#569]
The Spoon#copy method doesn't take into consideration the amount read into the buffer and writes the entire buffer, not up to the limit of the contents just read causing extra characters to be produced at the end of the file

**Comment by edenman** [comment]
Did you close the PR because this isn't actually an issue?

**Comment by sunyal** [comment]
It's an issue for the 1.7.1 tag. It has been corrected in the latest
codebase. But that leads me to the question when the next release will
occur.

**Comment by edenman** [comment]
Sorry, no estimate on release date
