### ISSUE TITLE
HTML Report Customization

### ISSUE THREAD

**Issue by cody1024d** [square/spoon#574]
Hey guys!  This project is awesome.  This is more of a feature request than a bug, but...

I was wondering if Report-Customization is on the roadmap at all?  There is additional information that I'd like to add to the HTML report (such as a small test description perhaps), without bloating the test name with that information.

**Comment by JakeWharton** [comment]
There are currently no plans to enhance this tool. Your best bet is to fork it and add whatever you need yourself.

**Comment by cody1024d** [comment]
Sounds good. will do that as needed.  Thanks for the quick reply @JakeWharton.

**Comment by cody1024d** [comment]
Sorry to necro this issue, I've got my use-case up and running, but have hit a snag, and wanted to see what you all thought about it.  

I wanted the reporter to be able to interrogate an annotation on the running tests, but now that I understand it a bit better, I see that this is not possible out of the box, because the testAPK is simply run through the adb command (and thus none of it's classes are in Spoon's class path).

The only solution I can think of is to load the testAPK dex into a classloader to be able to grab the annotations out as I'm listening to test results.  Thoughts?

**Comment by cody1024d** [comment]
We're going to solve the above problem leveraging: 
[Instrumentation.sendStatus](https://developer.android.com/reference/android/app/Instrumentation#sendStatus(int,%2520android.os.Bundle))

In case anyone comes to this in the future
