### ISSUE TITLE
Spoon fails to capture a screenshot due to a difference between the actual class hierarchy, and the expected class hierarchy

### ISSUE THREAD

**Issue by ncweinhold** [square/spoon#80]
We are using Spoon as part of our automated tests for an Android application.

We have code similar to:

```java
public class TestSample extends OurOwnInstrumentationClass {

    @Override
    public void setUp() {
        // does some set up common to our tests
        // captures a screenshot here
    }

    public void testSomethingOrOther() {
        // does a test here
    }

    public void testSomethingElse() {
        // does another test
    }
}
```

where OurOwnInstrumentationClass extends the ActivityInstrumentationTestCase2<T> of Android.

When running the test, Spoon fails to capture a screenshot, throwing an IllegalArgumentException stating that it cannot find the test class.

From debugging the tests, it seems to be a case that findTestClassTraceElement in Spoon.java expects to find android.test.InstrumentationTestCase on the stack, however due to where we are capturing the screenshot, we have junit.framework.TestCase on the stack instead, thus the exception is thrown.

Is there a way to adjust the code so that findTestClassTraceElement is not dependent on the hardcoded "android.test.InstrumentationTestCase" string?

**Comment by edenman** [comment]
In 1.1.4 we added the ability to specify the test/class name.  Closing this out.
